import { Order202309GetOrderListResponseDataOrdersHandlingDuration } from './GetOrderListResponseDataOrdersHandlingDuration';
import { Order202309GetOrderListResponseDataOrdersLineItems } from './GetOrderListResponseDataOrdersLineItems';
import { Order202309GetOrderListResponseDataOrdersPackages } from './GetOrderListResponseDataOrdersPackages';
import { Order202309GetOrderListResponseDataOrdersPayment } from './GetOrderListResponseDataOrdersPayment';
import { Order202309GetOrderListResponseDataOrdersRecipientAddress } from './GetOrderListResponseDataOrdersRecipientAddress';
export declare class Order202309GetOrderListResponseDataOrders {
    'autoCombineGroupId'?: string;
    'buyerEmail'?: string;
    'buyerMessage'?: string;
    'cancelOrderSlaTime'?: number;
    'cancelReason'?: string;
    'cancelTime'?: number;
    'cancellationInitiator'?: string;
    'collectionDueTime'?: number;
    'collectionTime'?: number;
    'commercePlatform'?: string;
    'consultationId'?: string;
    'cpf'?: string;
    'cpfName'?: string;
    'createTime'?: number;
    'deliveryDueTime'?: number;
    'deliveryOptionId'?: string;
    'deliveryOptionName'?: string;
    'deliveryOptionRequiredDeliveryTime'?: number;
    'deliverySlaTime'?: number;
    'deliveryTime'?: number;
    'deliveryType'?: string;
    'exchangeSourceOrderId'?: string;
    'fastDeliveryProgram'?: string;
    'fastDispatchSlaTime'?: number;
    'fulfillmentPriorityLevel'?: number;
    'fulfillmentType'?: string;
    'handlingDuration'?: Order202309GetOrderListResponseDataOrdersHandlingDuration;
    'hasUpdatedRecipientAddress'?: boolean;
    'id'?: string;
    'isBuyerRequestCancel'?: boolean;
    'isCod'?: boolean;
    'isExchangeOrder'?: boolean;
    'isOnHoldOrder'?: boolean;
    'isReplacementOrder'?: boolean;
    'isSampleOrder'?: boolean;
    'lineItems'?: Array<Order202309GetOrderListResponseDataOrdersLineItems>;
    'needUploadInvoice'?: string;
    'orderType'?: string;
    'packages'?: Array<Order202309GetOrderListResponseDataOrdersPackages>;
    'paidTime'?: number;
    'payment'?: Order202309GetOrderListResponseDataOrdersPayment;
    'paymentMethodName'?: string;
    'pickUpCutOffTime'?: number;
    'recipientAddress'?: Order202309GetOrderListResponseDataOrdersRecipientAddress;
    'recommendedShippingTime'?: number;
    'releaseDate'?: number;
    'replacedOrderId'?: string;
    'requestCancelTime'?: number;
    'rtsSlaTime'?: number;
    'rtsTime'?: number;
    'sellerNote'?: string;
    'shippingDueTime'?: number;
    'shippingProvider'?: string;
    'shippingProviderId'?: string;
    'shippingType'?: string;
    'splitOrCombineTag'?: string;
    'status'?: string;
    'trackingNumber'?: string;
    'ttsSlaTime'?: number;
    'updateTime'?: number;
    'userId'?: string;
    'warehouseId'?: string;
    static discriminator: string | undefined;
    static attributeTypeMap: Array<{
        name: string;
        baseName: string;
        type: string;
    }>;
    static getAttributeTypeMap(): {
        name: string;
        baseName: string;
        type: string;
    }[];
}
//# sourceMappingURL=GetOrderListResponseDataOrders.d.ts.map