/**
 * tiktok shop openapi
 * sdk for apis
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { RequestFile } from '../../models';
import { AffiliatePartner202501GetAffiliateCampaignCreatorProductSampleStatusResponseDataSampleStatusTrackingResults } from './GetAffiliateCampaignCreatorProductSampleStatusResponseDataSampleStatusTrackingResults';

export class AffiliatePartner202501GetAffiliateCampaignCreatorProductSampleStatusResponseDataSampleStatus {
    /**
    * The delivery option: - ECONOMY_SHIPPING - PREMIUM_SHIPPING 
    */
    'deliveryOption'?: string;
    /**
    * The earliest estimated delivery date in Unix epoch format.
    */
    'estimatedEarliestDeliveryDate'?: string;
    /**
    * The longest estimated delivery date in Unix epoch format.
    */
    'estimatedLatestDeliveryDate'?: string;
    /**
    * The quantity of products delivered.
    */
    'quantity'?: number;
    /**
    * The name of the shipping provider
    */
    'shippingProviderName'?: string;
    /**
    * A list of objects representing tracking events.
    */
    'trackingResults'?: Array<AffiliatePartner202501GetAffiliateCampaignCreatorProductSampleStatusResponseDataSampleStatusTrackingResults>;

    static discriminator: string | undefined = undefined;

    static attributeTypeMap: Array<{name: string, baseName: string, type: string}> = [
        {
            "name": "deliveryOption",
            "baseName": "delivery_option",
            "type": "string"
        },
        {
            "name": "estimatedEarliestDeliveryDate",
            "baseName": "estimated_earliest_delivery_date",
            "type": "string"
        },
        {
            "name": "estimatedLatestDeliveryDate",
            "baseName": "estimated_latest_delivery_date",
            "type": "string"
        },
        {
            "name": "quantity",
            "baseName": "quantity",
            "type": "number"
        },
        {
            "name": "shippingProviderName",
            "baseName": "shipping_provider_name",
            "type": "string"
        },
        {
            "name": "trackingResults",
            "baseName": "tracking_results",
            "type": "Array<AffiliatePartner202501GetAffiliateCampaignCreatorProductSampleStatusResponseDataSampleStatusTrackingResults>"
        }    ];

    static getAttributeTypeMap() {
        return AffiliatePartner202501GetAffiliateCampaignCreatorProductSampleStatusResponseDataSampleStatus.attributeTypeMap;
    }
}

