/**
 * tiktok shop openapi
 * sdk for apis
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { RequestFile } from '../../models';
import { AffiliatePartner202501GetAffiliateCampaignCreatorFulfillmentStatusInfoResponseDataPromotionCreators } from './GetAffiliateCampaignCreatorFulfillmentStatusInfoResponseDataPromotionCreators';

export class AffiliatePartner202501GetAffiliateCampaignCreatorFulfillmentStatusInfoResponseData {
    /**
    * Querying next page need this token.
    */
    'nextPageToken'?: string;
    /**
    * A list of objects representing information about the Affiliate Creator associated with the product promotion.
    */
    'promotionCreators'?: Array<AffiliatePartner202501GetAffiliateCampaignCreatorFulfillmentStatusInfoResponseDataPromotionCreators>;
    /**
    * The total number of creators involved in the campaign.
    */
    'totalCreatorCount'?: number;

    static discriminator: string | undefined = undefined;

    static attributeTypeMap: Array<{name: string, baseName: string, type: string}> = [
        {
            "name": "nextPageToken",
            "baseName": "next_page_token",
            "type": "string"
        },
        {
            "name": "promotionCreators",
            "baseName": "promotion_creators",
            "type": "Array<AffiliatePartner202501GetAffiliateCampaignCreatorFulfillmentStatusInfoResponseDataPromotionCreators>"
        },
        {
            "name": "totalCreatorCount",
            "baseName": "total_creator_count",
            "type": "number"
        }    ];

    static getAttributeTypeMap() {
        return AffiliatePartner202501GetAffiliateCampaignCreatorFulfillmentStatusInfoResponseData.attributeTypeMap;
    }
}

