/**
 * tiktok shop openapi
 * sdk for apis
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { RequestFile } from '../../models';

export class AffiliatePartner202501GetAffiliateCampaignCreatorFulfillmentStatusListResponseDataCampaignProductStatisticsCampaignProductDetailIndicatorData {
    /**
    * GMV, the total payment amount corresponding to `actual_order_num`. 
    */
    'actualAmount'?: string;
    /**
    * The actual number of paid orders. 
    */
    'actualOrderNum'?: string;
    /**
    * The partner commission amount corresponding to actual_order_num. 
    */
    'actualPartnerCommission'?: string;
    /**
    * The total number of creators collaborating on the campaign.
    */
    'collaboratedCreatorsNum'?: string;
    /**
    * The number of creators credited with at least one product sale.
    */
    'creatorSalesNum'?: string;
    /**
    * The total payment amount corresponding to `paid_order_num`. 
    */
    'estimatedAmount'?: string;
    /**
    * The partner commission amount corresponding to paid_order_num. 
    */
    'estimatedPartnerCommission'?: string;
    /**
    * The total number of paid orders. `paid_order_num` = `actual_order_num` + {number of paid but returned orders} 
    */
    'paidOrderNum'?: string;
    /**
    * The number of creators involved in the partner plan. 
    */
    'promotedCreatorNum'?: string;
    /**
    * The total number of creators that applied for a sample.
    */
    'sampleRequestedCreatorNum'?: string;

    static discriminator: string | undefined = undefined;

    static attributeTypeMap: Array<{name: string, baseName: string, type: string}> = [
        {
            "name": "actualAmount",
            "baseName": "actual_amount",
            "type": "string"
        },
        {
            "name": "actualOrderNum",
            "baseName": "actual_order_num",
            "type": "string"
        },
        {
            "name": "actualPartnerCommission",
            "baseName": "actual_partner_commission",
            "type": "string"
        },
        {
            "name": "collaboratedCreatorsNum",
            "baseName": "collaborated_creators_num",
            "type": "string"
        },
        {
            "name": "creatorSalesNum",
            "baseName": "creator_sales_num",
            "type": "string"
        },
        {
            "name": "estimatedAmount",
            "baseName": "estimated_amount",
            "type": "string"
        },
        {
            "name": "estimatedPartnerCommission",
            "baseName": "estimated_partner_commission",
            "type": "string"
        },
        {
            "name": "paidOrderNum",
            "baseName": "paid_order_num",
            "type": "string"
        },
        {
            "name": "promotedCreatorNum",
            "baseName": "promoted_creator_num",
            "type": "string"
        },
        {
            "name": "sampleRequestedCreatorNum",
            "baseName": "sample_requested_creator_num",
            "type": "string"
        }    ];

    static getAttributeTypeMap() {
        return AffiliatePartner202501GetAffiliateCampaignCreatorFulfillmentStatusListResponseDataCampaignProductStatisticsCampaignProductDetailIndicatorData.attributeTypeMap;
    }
}

