/**
 * tiktok shop openapi
 * sdk for apis
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { RequestFile } from '../../models';
import { AffiliatePartner202501GetAffiliateCampaignCreatorFulfillmentStatusListResponseDataCampaignProductStatistics } from './GetAffiliateCampaignCreatorFulfillmentStatusListResponseDataCampaignProductStatistics';

export class AffiliatePartner202501GetAffiliateCampaignCreatorFulfillmentStatusListResponseData {
    /**
    * A list of objects representing campaign product statistics.
    */
    'campaignProductStatistics'?: Array<AffiliatePartner202501GetAffiliateCampaignCreatorFulfillmentStatusListResponseDataCampaignProductStatistics>;
    /**
    * next page query token
    */
    'nextPageToken'?: string;
    /**
    * The total count of products included in the specified campaign.
    */
    'totalCount'?: number;

    static discriminator: string | undefined = undefined;

    static attributeTypeMap: Array<{name: string, baseName: string, type: string}> = [
        {
            "name": "campaignProductStatistics",
            "baseName": "campaign_product_statistics",
            "type": "Array<AffiliatePartner202501GetAffiliateCampaignCreatorFulfillmentStatusListResponseDataCampaignProductStatistics>"
        },
        {
            "name": "nextPageToken",
            "baseName": "next_page_token",
            "type": "string"
        },
        {
            "name": "totalCount",
            "baseName": "total_count",
            "type": "number"
        }    ];

    static getAttributeTypeMap() {
        return AffiliatePartner202501GetAffiliateCampaignCreatorFulfillmentStatusListResponseData.attributeTypeMap;
    }
}

