/**
 * tiktok shop openapi
 * sdk for apis
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { RequestFile } from '../../models';

export class AffiliatePartner202501GetAffiliateCampaignCreatorFulfillmentStatusInfoResponseDataPromotionCreatorsCreator {
    /**
    * A URL for the creator\'s avatar image in the TikTok CDN.
    */
    'avatarUrl'?: string;
    /**
    * A time-limited identifier associated with the creator that is valid for one hour. This identifier is valid to retrieve content performance data associated with the creator.
    */
    'creatorTempId'?: string;
    /**
    * The total count of TikTok followers for the creator.
    */
    'followerNum'?: number;
    /**
    * The TikTok nickname of the creator.
    */
    'nickName'?: string;
    /**
    * user name
    */
    'userName'?: string;

    static discriminator: string | undefined = undefined;

    static attributeTypeMap: Array<{name: string, baseName: string, type: string}> = [
        {
            "name": "avatarUrl",
            "baseName": "avatar_url",
            "type": "string"
        },
        {
            "name": "creatorTempId",
            "baseName": "creator_temp_id",
            "type": "string"
        },
        {
            "name": "followerNum",
            "baseName": "follower_num",
            "type": "number"
        },
        {
            "name": "nickName",
            "baseName": "nick_name",
            "type": "string"
        },
        {
            "name": "userName",
            "baseName": "user_name",
            "type": "string"
        }    ];

    static getAttributeTypeMap() {
        return AffiliatePartner202501GetAffiliateCampaignCreatorFulfillmentStatusInfoResponseDataPromotionCreatorsCreator.attributeTypeMap;
    }
}

