/**
 * tiktok shop openapi
 * sdk for apis
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { RequestFile } from '../../models';
import { AffiliatePartner202501GetAffiliateCampaignCreatorProductContentStatisticsResponseDataCreatorContentStatistics } from './GetAffiliateCampaignCreatorProductContentStatisticsResponseDataCreatorContentStatistics';

export class AffiliatePartner202501GetAffiliateCampaignCreatorProductContentStatisticsResponseData {
    /**
    * A list of objects that represent content statistics for the associated creator.
    */
    'creatorContentStatistics'?: Array<AffiliatePartner202501GetAffiliateCampaignCreatorProductContentStatisticsResponseDataCreatorContentStatistics>;

    static discriminator: string | undefined = undefined;

    static attributeTypeMap: Array<{name: string, baseName: string, type: string}> = [
        {
            "name": "creatorContentStatistics",
            "baseName": "creator_content_statistics",
            "type": "Array<AffiliatePartner202501GetAffiliateCampaignCreatorProductContentStatisticsResponseDataCreatorContentStatistics>"
        }    ];

    static getAttributeTypeMap() {
        return AffiliatePartner202501GetAffiliateCampaignCreatorProductContentStatisticsResponseData.attributeTypeMap;
    }
}

