/**
 * tiktok shop openapi
 * sdk for apis
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { RequestFile } from '../../models';
import { AffiliatePartner202501GetAffiliateCampaignCreatorFulfillmentStatusListResponseDataCampaignProductStatisticsCampaignProductDetailIndicatorData } from './GetAffiliateCampaignCreatorFulfillmentStatusListResponseDataCampaignProductStatisticsCampaignProductDetailIndicatorData';
import { AffiliatePartner202501GetAffiliateCampaignCreatorFulfillmentStatusListResponseDataCampaignProductStatisticsCampaignProductDetailProductPrice } from './GetAffiliateCampaignCreatorFulfillmentStatusListResponseDataCampaignProductStatisticsCampaignProductDetailProductPrice';
import { AffiliatePartner202501GetAffiliateCampaignCreatorFulfillmentStatusListResponseDataCampaignProductStatisticsCampaignProductDetailProductThumbnail } from './GetAffiliateCampaignCreatorFulfillmentStatusListResponseDataCampaignProductStatisticsCampaignProductDetailProductThumbnail';

export class AffiliatePartner202501GetAffiliateCampaignCreatorFulfillmentStatusListResponseDataCampaignProductStatisticsCampaignProductDetail {
    /**
    * The commission rate for the creator in the partner plan. The value is in hundredths of a percent. For example, a value of 1000 means 10.00%.
    */
    'creatorCommissionPercent'?: string;
    'indicatorData'?: AffiliatePartner202501GetAffiliateCampaignCreatorFulfillmentStatusListResponseDataCampaignProductStatisticsCampaignProductDetailIndicatorData;
    /**
    * The commission rate for the partner in the partner plan. The value is in hundredths of a percent. For example, a value of 1000 means 10.00%. 
    */
    'partnerCommissionPercent'?: string;
    /**
    * The commission rate for open collaboration. The value is in hundredths of a percent. For example, a value of 1000 means 10.00%. 
    */
    'planCommissionPercent'?: string;
    /**
    * The product identifier.
    */
    'productId'?: string;
    /**
    * The product name.
    */
    'productName'?: string;
    'productPrice'?: AffiliatePartner202501GetAffiliateCampaignCreatorFulfillmentStatusListResponseDataCampaignProductStatisticsCampaignProductDetailProductPrice;
    /**
    * The product status. This is an enumerated type with values: -  PRODUCT_UNSPECIFIED -  PRODUCT_PENDING -  PRODUCT_APPROVED -  PRODUCT_REJECTED -  PRODUCT_PENDING_CLOSED -  PRODUCT_CLOSED 
    */
    'productStatus'?: string;
    /**
    * The total number of products in stock.
    */
    'productStockCount'?: string;
    'productThumbnail'?: AffiliatePartner202501GetAffiliateCampaignCreatorFulfillmentStatusListResponseDataCampaignProductStatisticsCampaignProductDetailProductThumbnail;
    /**
    * The commission rate of the partner plan. It is the sum of the `creator_commission_rate` and `partner_commission_rate`. The value is in hundredths of a percent. For example, a value of 1000 means 10.00%. 
    */
    'totalCommissionPercent'?: string;

    static discriminator: string | undefined = undefined;

    static attributeTypeMap: Array<{name: string, baseName: string, type: string}> = [
        {
            "name": "creatorCommissionPercent",
            "baseName": "creator_commission_percent",
            "type": "string"
        },
        {
            "name": "indicatorData",
            "baseName": "indicator_data",
            "type": "AffiliatePartner202501GetAffiliateCampaignCreatorFulfillmentStatusListResponseDataCampaignProductStatisticsCampaignProductDetailIndicatorData"
        },
        {
            "name": "partnerCommissionPercent",
            "baseName": "partner_commission_percent",
            "type": "string"
        },
        {
            "name": "planCommissionPercent",
            "baseName": "plan_commission_percent",
            "type": "string"
        },
        {
            "name": "productId",
            "baseName": "product_id",
            "type": "string"
        },
        {
            "name": "productName",
            "baseName": "product_name",
            "type": "string"
        },
        {
            "name": "productPrice",
            "baseName": "product_price",
            "type": "AffiliatePartner202501GetAffiliateCampaignCreatorFulfillmentStatusListResponseDataCampaignProductStatisticsCampaignProductDetailProductPrice"
        },
        {
            "name": "productStatus",
            "baseName": "product_status",
            "type": "string"
        },
        {
            "name": "productStockCount",
            "baseName": "product_stock_count",
            "type": "string"
        },
        {
            "name": "productThumbnail",
            "baseName": "product_thumbnail",
            "type": "AffiliatePartner202501GetAffiliateCampaignCreatorFulfillmentStatusListResponseDataCampaignProductStatisticsCampaignProductDetailProductThumbnail"
        },
        {
            "name": "totalCommissionPercent",
            "baseName": "total_commission_percent",
            "type": "string"
        }    ];

    static getAttributeTypeMap() {
        return AffiliatePartner202501GetAffiliateCampaignCreatorFulfillmentStatusListResponseDataCampaignProductStatisticsCampaignProductDetail.attributeTypeMap;
    }
}

