/**
 * tiktok shop openapi
 * sdk for apis
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { RequestFile } from '../../models';

export class AffiliatePartner202501GetAffiliateCampaignCreatorProductSampleStatusResponseDataSampleStatusTrackingResults {
    /**
    * The title of the tracking event. - THE_PACKAGE_HAS_BEEN_DELIVERED - OUT_FOR_DELIVERY - ORDER_PACKED_AND_READY_FOR_DROP_OFF_AT_CARRIERS_FACILITY - ORDER_PLACED
    */
    'trackingEventDescription'?: string;
    /**
    *  More information about the tracking event
    */
    'trackingEventDescriptionExtended'?: string;
    /**
    * The date at which the tracking event was last updated, in Unix epoch format.
    */
    'trackingEventUpdateDate'?: string;

    static discriminator: string | undefined = undefined;

    static attributeTypeMap: Array<{name: string, baseName: string, type: string}> = [
        {
            "name": "trackingEventDescription",
            "baseName": "tracking_event_description",
            "type": "string"
        },
        {
            "name": "trackingEventDescriptionExtended",
            "baseName": "tracking_event_description_extended",
            "type": "string"
        },
        {
            "name": "trackingEventUpdateDate",
            "baseName": "tracking_event_update_date",
            "type": "string"
        }    ];

    static getAttributeTypeMap() {
        return AffiliatePartner202501GetAffiliateCampaignCreatorProductSampleStatusResponseDataSampleStatusTrackingResults.attributeTypeMap;
    }
}

