/**
 * tiktok shop openapi
 * sdk for apis
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { RequestFile } from '../../models';
import { AffiliatePartner202501GetAffiliateCampaignCreatorFulfillmentStatusInfoResponseDataPromotionCreatorsCreator } from './GetAffiliateCampaignCreatorFulfillmentStatusInfoResponseDataPromotionCreatorsCreator';
import { AffiliatePartner202501GetAffiliateCampaignCreatorFulfillmentStatusInfoResponseDataPromotionCreatorsPaidAmount } from './GetAffiliateCampaignCreatorFulfillmentStatusInfoResponseDataPromotionCreatorsPaidAmount';

export class AffiliatePartner202501GetAffiliateCampaignCreatorFulfillmentStatusInfoResponseDataPromotionCreators {
    /**
    * The affiliate product identifier.
    */
    'affiliateProductId'?: string;
    /**
    * The commission rate in hundredths of a percent (0.01%). For example, a value of 1000 is 10.00%.
    */
    'commission'?: string;
    'creator'?: AffiliatePartner202501GetAffiliateCampaignCreatorFulfillmentStatusInfoResponseDataPromotionCreatorsCreator;
    /**
    * The effective end time for the collaboration in Unix epoch time format.
    */
    'effectiveEndTime'?: string;
    /**
    * The effective start time for the collaboration in Unix epoch time format.
    */
    'effectiveStartTime'?: string;
    /**
    * Status of the Creator\'s sample application. - NOT_REQUESTED - PENDING - AWAITING_SHIPMENT - AWAITING_COLLECTION - SHIPPED - CONTENT_PENDING - REJECT_CANCELLED - OVERDUE_CANCELLED - UNFULFIL_CANCELLED - DEL_PLAN_CANCELLED - SELLER_NOT_SHIP_CANCELLED - WITHDRAW_CANCELLED - UNFULFILLABLE_CANCELLED - OPERATOR_MANUAL_CANCELLED - OPERATOR_MANUAL_FAILED - OPERATOR_MANUAL_COMPLETED - COMPLETED
    */
    'freeSampleStatus'?: string;
    'paidAmount'?: AffiliatePartner202501GetAffiliateCampaignCreatorFulfillmentStatusInfoResponseDataPromotionCreatorsPaidAmount;
    /**
    * The number of live broadcast rooms associated with this promotion.
    */
    'roomCount'?: number;
    /**
    * The total number of videos associated with this promotion published by creators.
    */
    'videoCount'?: number;

    static discriminator: string | undefined = undefined;

    static attributeTypeMap: Array<{name: string, baseName: string, type: string}> = [
        {
            "name": "affiliateProductId",
            "baseName": "affiliate_product_id",
            "type": "string"
        },
        {
            "name": "commission",
            "baseName": "commission",
            "type": "string"
        },
        {
            "name": "creator",
            "baseName": "creator",
            "type": "AffiliatePartner202501GetAffiliateCampaignCreatorFulfillmentStatusInfoResponseDataPromotionCreatorsCreator"
        },
        {
            "name": "effectiveEndTime",
            "baseName": "effective_end_time",
            "type": "string"
        },
        {
            "name": "effectiveStartTime",
            "baseName": "effective_start_time",
            "type": "string"
        },
        {
            "name": "freeSampleStatus",
            "baseName": "free_sample_status",
            "type": "string"
        },
        {
            "name": "paidAmount",
            "baseName": "paid_amount",
            "type": "AffiliatePartner202501GetAffiliateCampaignCreatorFulfillmentStatusInfoResponseDataPromotionCreatorsPaidAmount"
        },
        {
            "name": "roomCount",
            "baseName": "room_count",
            "type": "number"
        },
        {
            "name": "videoCount",
            "baseName": "video_count",
            "type": "number"
        }    ];

    static getAttributeTypeMap() {
        return AffiliatePartner202501GetAffiliateCampaignCreatorFulfillmentStatusInfoResponseDataPromotionCreators.attributeTypeMap;
    }
}

