/**
 * tiktok shop openapi
 * sdk for apis
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { RequestFile } from '../../models';
import { AffiliatePartner202501GetAffiliateCampaignCreatorFulfillmentStatusListResponseDataCampaignProductStatisticsCampaignProductDetail } from './GetAffiliateCampaignCreatorFulfillmentStatusListResponseDataCampaignProductStatisticsCampaignProductDetail';

export class AffiliatePartner202501GetAffiliateCampaignCreatorFulfillmentStatusListResponseDataCampaignProductStatistics {
    'campaignProductDetail'?: AffiliatePartner202501GetAffiliateCampaignCreatorFulfillmentStatusListResponseDataCampaignProductStatisticsCampaignProductDetail;
    /**
    * The total number of creators associated with the campaign.
    */
    'collaboratedCreatorsNum'?: number;
    /**
    * The number of products sold in the campaign.
    */
    'creatorSalesNum'?: number;
    /**
    * The time at which the product data was last updated, in Unix epoch format.
    */
    'dataUpdateTime'?: string;
    /**
    * The number of the creators involved in the campaign. 
    */
    'promotedCreatorNum'?: number;
    /**
    * The total number of samples requested by all creators associated with the campaign. 
    */
    'sampleRequestedCreatorNum'?: number;

    static discriminator: string | undefined = undefined;

    static attributeTypeMap: Array<{name: string, baseName: string, type: string}> = [
        {
            "name": "campaignProductDetail",
            "baseName": "campaign_product_detail",
            "type": "AffiliatePartner202501GetAffiliateCampaignCreatorFulfillmentStatusListResponseDataCampaignProductStatisticsCampaignProductDetail"
        },
        {
            "name": "collaboratedCreatorsNum",
            "baseName": "collaborated_creators_num",
            "type": "number"
        },
        {
            "name": "creatorSalesNum",
            "baseName": "creator_sales_num",
            "type": "number"
        },
        {
            "name": "dataUpdateTime",
            "baseName": "data_update_time",
            "type": "string"
        },
        {
            "name": "promotedCreatorNum",
            "baseName": "promoted_creator_num",
            "type": "number"
        },
        {
            "name": "sampleRequestedCreatorNum",
            "baseName": "sample_requested_creator_num",
            "type": "number"
        }    ];

    static getAttributeTypeMap() {
        return AffiliatePartner202501GetAffiliateCampaignCreatorFulfillmentStatusListResponseDataCampaignProductStatistics.attributeTypeMap;
    }
}

