/**
 * tiktok shop openapi
 * sdk for apis
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { RequestFile } from '../../models';
import { AffiliatePartner202411SearchTapAffiliateOrdersResponseDataOrdersSkus } from './SearchTapAffiliateOrdersResponseDataOrdersSkus';

export class AffiliatePartner202411SearchTapAffiliateOrdersResponseDataOrders {
    /**
    * Time and date of order created, UTC+0 timing
    */
    'createTime'?: number;
    /**
    * Time and date order delivered, UTC+0 timing
    */
    'deliveryTime'?: number;
    /**
    * Transaction main order ID
    */
    'id'?: string;
    'skus'?: AffiliatePartner202411SearchTapAffiliateOrdersResponseDataOrdersSkus;
    /**
    * Status order for product sales The order status. Possible values: 1. \"ALL\" 2. \"PROCESSING\" 3. \"COMPLETED\" 4. \"CANCELLED\" 5. \"FROZEN\" 6. \"DEDUCTED\"
    */
    'status'?: string;

    static discriminator: string | undefined = undefined;

    static attributeTypeMap: Array<{name: string, baseName: string, type: string}> = [
        {
            "name": "createTime",
            "baseName": "create_time",
            "type": "number"
        },
        {
            "name": "deliveryTime",
            "baseName": "delivery_time",
            "type": "number"
        },
        {
            "name": "id",
            "baseName": "id",
            "type": "string"
        },
        {
            "name": "skus",
            "baseName": "skus",
            "type": "AffiliatePartner202411SearchTapAffiliateOrdersResponseDataOrdersSkus"
        },
        {
            "name": "status",
            "baseName": "status",
            "type": "string"
        }    ];

    static getAttributeTypeMap() {
        return AffiliatePartner202411SearchTapAffiliateOrdersResponseDataOrders.attributeTypeMap;
    }
}

