/**
 * tiktok shop openapi
 * sdk for apis
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { RequestFile } from '../../models';
import { AffiliatePartner202411SearchTapAffiliateOrdersResponseDataOrdersSkusActualCommissionBase } from './SearchTapAffiliateOrdersResponseDataOrdersSkusActualCommissionBase';
import { AffiliatePartner202411SearchTapAffiliateOrdersResponseDataOrdersSkusActualCreatorCommission } from './SearchTapAffiliateOrdersResponseDataOrdersSkusActualCreatorCommission';
import { AffiliatePartner202411SearchTapAffiliateOrdersResponseDataOrdersSkusActualCreatorCommissionRewardFee } from './SearchTapAffiliateOrdersResponseDataOrdersSkusActualCreatorCommissionRewardFee';
import { AffiliatePartner202411SearchTapAffiliateOrdersResponseDataOrdersSkusActualPartnerCommissionRewardFee } from './SearchTapAffiliateOrdersResponseDataOrdersSkusActualPartnerCommissionRewardFee';
import { AffiliatePartner202411SearchTapAffiliateOrdersResponseDataOrdersSkusActualTapCommission } from './SearchTapAffiliateOrdersResponseDataOrdersSkusActualTapCommission';
import { AffiliatePartner202411SearchTapAffiliateOrdersResponseDataOrdersSkusEstimatedCommissionBase } from './SearchTapAffiliateOrdersResponseDataOrdersSkusEstimatedCommissionBase';
import { AffiliatePartner202411SearchTapAffiliateOrdersResponseDataOrdersSkusEstimatedCreatorCommission } from './SearchTapAffiliateOrdersResponseDataOrdersSkusEstimatedCreatorCommission';
import { AffiliatePartner202411SearchTapAffiliateOrdersResponseDataOrdersSkusEstimatedCreatorCommissionRewardFee } from './SearchTapAffiliateOrdersResponseDataOrdersSkusEstimatedCreatorCommissionRewardFee';
import { AffiliatePartner202411SearchTapAffiliateOrdersResponseDataOrdersSkusEstimatedPartnerCommissionRewardFee } from './SearchTapAffiliateOrdersResponseDataOrdersSkusEstimatedPartnerCommissionRewardFee';
import { AffiliatePartner202411SearchTapAffiliateOrdersResponseDataOrdersSkusEstimatedTapCommission } from './SearchTapAffiliateOrdersResponseDataOrdersSkusEstimatedTapCommission';
import { AffiliatePartner202411SearchTapAffiliateOrdersResponseDataOrdersSkusPrice } from './SearchTapAffiliateOrdersResponseDataOrdersSkusPrice';

export class AffiliatePartner202411SearchTapAffiliateOrdersResponseDataOrdersSkus {
    'actualCommissionBase'?: AffiliatePartner202411SearchTapAffiliateOrdersResponseDataOrdersSkusActualCommissionBase;
    'actualCreatorCommission'?: AffiliatePartner202411SearchTapAffiliateOrdersResponseDataOrdersSkusActualCreatorCommission;
    'actualCreatorCommissionRewardFee'?: AffiliatePartner202411SearchTapAffiliateOrdersResponseDataOrdersSkusActualCreatorCommissionRewardFee;
    'actualPartnerCommissionRewardFee'?: AffiliatePartner202411SearchTapAffiliateOrdersResponseDataOrdersSkusActualPartnerCommissionRewardFee;
    'actualTapCommission'?: AffiliatePartner202411SearchTapAffiliateOrdersResponseDataOrdersSkusActualTapCommission;
    /**
    * New seller campaign 
    */
    'campaignId'?: string;
    /**
    * Unique identifier for content
    */
    'contentId'?: string;
    /**
    * The content format of the creator content through which the order was created. Possible values: - SHOP - VIDEO - LIVE - PRE_LIVE - PROMOTION_PAGE - LINKSHARE
    */
    'contentType'?: string;
    /**
    * Between TAP & creator percentage commission
    */
    'creatorCommissionRate'?: number;
    /**
    * The commission reward rate affiliate partners allocate to creators
    */
    'creatorCommissionRewardRate'?: number;
    /**
    * Creator username
    */
    'creatorUsername'?: string;
    'estimatedCommissionBase'?: AffiliatePartner202411SearchTapAffiliateOrdersResponseDataOrdersSkusEstimatedCommissionBase;
    'estimatedCreatorCommission'?: AffiliatePartner202411SearchTapAffiliateOrdersResponseDataOrdersSkusEstimatedCreatorCommission;
    'estimatedCreatorCommissionRewardFee'?: AffiliatePartner202411SearchTapAffiliateOrdersResponseDataOrdersSkusEstimatedCreatorCommissionRewardFee;
    'estimatedPartnerCommissionRewardFee'?: AffiliatePartner202411SearchTapAffiliateOrdersResponseDataOrdersSkusEstimatedPartnerCommissionRewardFee;
    'estimatedTapCommission'?: AffiliatePartner202411SearchTapAffiliateOrdersResponseDataOrdersSkusEstimatedTapCommission;
    /**
    * sku ID
    */
    'id'?: string;
    /**
    * The additional commission rate TikTok Shop offers to affiliate partners for driving product sales in specific campaigns
    */
    'partnerCommissionRewardRate'?: number;
    'price'?: AffiliatePartner202411SearchTapAffiliateOrdersResponseDataOrdersSkusPrice;
    /**
    * Unique identifier for Product
    */
    'productId'?: string;
    /**
    * Product name / description
    */
    'productName'?: string;
    /**
    * Total sku quantity per order
    */
    'quantity'?: number;
    /**
    * Number of sku refunded per order
    */
    'refundedQuantity'?: number;
    /**
    * Number of sku returned per order
    */
    'returnedQuantity'?: number;
    /**
    * Between seller & TAP percentage commission
    */
    'tapCommissionRate'?: number;

    static discriminator: string | undefined = undefined;

    static attributeTypeMap: Array<{name: string, baseName: string, type: string}> = [
        {
            "name": "actualCommissionBase",
            "baseName": "actual_commission_base",
            "type": "AffiliatePartner202411SearchTapAffiliateOrdersResponseDataOrdersSkusActualCommissionBase"
        },
        {
            "name": "actualCreatorCommission",
            "baseName": "actual_creator_commission",
            "type": "AffiliatePartner202411SearchTapAffiliateOrdersResponseDataOrdersSkusActualCreatorCommission"
        },
        {
            "name": "actualCreatorCommissionRewardFee",
            "baseName": "actual_creator_commission_reward_fee",
            "type": "AffiliatePartner202411SearchTapAffiliateOrdersResponseDataOrdersSkusActualCreatorCommissionRewardFee"
        },
        {
            "name": "actualPartnerCommissionRewardFee",
            "baseName": "actual_partner_commission_reward_fee",
            "type": "AffiliatePartner202411SearchTapAffiliateOrdersResponseDataOrdersSkusActualPartnerCommissionRewardFee"
        },
        {
            "name": "actualTapCommission",
            "baseName": "actual_tap_commission",
            "type": "AffiliatePartner202411SearchTapAffiliateOrdersResponseDataOrdersSkusActualTapCommission"
        },
        {
            "name": "campaignId",
            "baseName": "campaign_id",
            "type": "string"
        },
        {
            "name": "contentId",
            "baseName": "content_id",
            "type": "string"
        },
        {
            "name": "contentType",
            "baseName": "content_type",
            "type": "string"
        },
        {
            "name": "creatorCommissionRate",
            "baseName": "creator_commission_rate",
            "type": "number"
        },
        {
            "name": "creatorCommissionRewardRate",
            "baseName": "creator_commission_reward_rate",
            "type": "number"
        },
        {
            "name": "creatorUsername",
            "baseName": "creator_username",
            "type": "string"
        },
        {
            "name": "estimatedCommissionBase",
            "baseName": "estimated_commission_base",
            "type": "AffiliatePartner202411SearchTapAffiliateOrdersResponseDataOrdersSkusEstimatedCommissionBase"
        },
        {
            "name": "estimatedCreatorCommission",
            "baseName": "estimated_creator_commission",
            "type": "AffiliatePartner202411SearchTapAffiliateOrdersResponseDataOrdersSkusEstimatedCreatorCommission"
        },
        {
            "name": "estimatedCreatorCommissionRewardFee",
            "baseName": "estimated_creator_commission_reward_fee",
            "type": "AffiliatePartner202411SearchTapAffiliateOrdersResponseDataOrdersSkusEstimatedCreatorCommissionRewardFee"
        },
        {
            "name": "estimatedPartnerCommissionRewardFee",
            "baseName": "estimated_partner_commission_reward_fee",
            "type": "AffiliatePartner202411SearchTapAffiliateOrdersResponseDataOrdersSkusEstimatedPartnerCommissionRewardFee"
        },
        {
            "name": "estimatedTapCommission",
            "baseName": "estimated_tap_commission",
            "type": "AffiliatePartner202411SearchTapAffiliateOrdersResponseDataOrdersSkusEstimatedTapCommission"
        },
        {
            "name": "id",
            "baseName": "id",
            "type": "string"
        },
        {
            "name": "partnerCommissionRewardRate",
            "baseName": "partner_commission_reward_rate",
            "type": "number"
        },
        {
            "name": "price",
            "baseName": "price",
            "type": "AffiliatePartner202411SearchTapAffiliateOrdersResponseDataOrdersSkusPrice"
        },
        {
            "name": "productId",
            "baseName": "product_id",
            "type": "string"
        },
        {
            "name": "productName",
            "baseName": "product_name",
            "type": "string"
        },
        {
            "name": "quantity",
            "baseName": "quantity",
            "type": "number"
        },
        {
            "name": "refundedQuantity",
            "baseName": "refunded_quantity",
            "type": "number"
        },
        {
            "name": "returnedQuantity",
            "baseName": "returned_quantity",
            "type": "number"
        },
        {
            "name": "tapCommissionRate",
            "baseName": "tap_commission_rate",
            "type": "number"
        }    ];

    static getAttributeTypeMap() {
        return AffiliatePartner202411SearchTapAffiliateOrdersResponseDataOrdersSkus.attributeTypeMap;
    }
}

