/**
 * tiktok shop openapi
 * sdk for apis
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { RequestFile } from '../../models';
import { AffiliatePartner202411SearchTapAffiliateOrdersResponseDataOrders } from './SearchTapAffiliateOrdersResponseDataOrders';

export class AffiliatePartner202411SearchTapAffiliateOrdersResponseData {
    /**
    * Cursor used for searching for more information
    */
    'nextPageToken'?: string;
    /**
    * Order list
    */
    'orders'?: Array<AffiliatePartner202411SearchTapAffiliateOrdersResponseDataOrders>;
    /**
    * The total number of orders
    */
    'totalCount'?: number;

    static discriminator: string | undefined = undefined;

    static attributeTypeMap: Array<{name: string, baseName: string, type: string}> = [
        {
            "name": "nextPageToken",
            "baseName": "next_page_token",
            "type": "string"
        },
        {
            "name": "orders",
            "baseName": "orders",
            "type": "Array<AffiliatePartner202411SearchTapAffiliateOrdersResponseDataOrders>"
        },
        {
            "name": "totalCount",
            "baseName": "total_count",
            "type": "number"
        }    ];

    static getAttributeTypeMap() {
        return AffiliatePartner202411SearchTapAffiliateOrdersResponseData.attributeTypeMap;
    }
}

