/**
 * tiktok shop openapi
 * sdk for apis
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { RequestFile } from '../../models';
import { AffiliatePartner202405CreateAffiliatePartnerCampaignRequestBodyContactInfo } from './CreateAffiliatePartnerCampaignRequestBodyContactInfo';

export class AffiliatePartner202405CreateAffiliatePartnerCampaignRequestBody {
    /**
    * The scheduled end time in Unix epoch time format for the campaign. Note that the end time must be less than 360 days from the start date. This field is no longer editable when the campaign status is set to `CLOSED`.
    */
    'campaignEndTime'?: number;
    /**
    * The scheduled start time in Unix epoch time format for the campaign. Note that this field can be updated when the campaign status is set to `READY` or `UPCOMING` only.
    */
    'campaignStartTime'?: number;
    /**
    * The total commission rate in hundredths of a percent (0.01%) units proposed by the affiliate partner for display to sellers. Commission rate must be greater than 100 and less than 8000.
    */
    'commissionRate'?: number;
    'contactInfo'?: AffiliatePartner202405CreateAffiliatePartnerCampaignRequestBodyContactInfo;
    /**
    * The campaign description. The campaign description must be less than 1000 characters.
    */
    'description'?: string;
    /**
    * The campaign name. The campaign name must be less than 50 characters.
    */
    'name'?: string;
    /**
    * The scheduled end time in Unix epoch time format for seller product registration. This field is no longer editable when the campaign status is set to `CLOSED`.
    */
    'registrationEndTime'?: number;
    /**
    * The scheduled start time in Unix epoch format for seller product registration. Note that this field can be updated when the campaign status is set to `READY` or `UPCOMING` only.
    */
    'registrationStartTime'?: number;
    /**
    * A list of eligible seller types to allow to register for the campaign. Use this field to broadly target types of sellers instead of specific sellers in the `target_shop_codes` field. This is an enumerated type with possible values: - LOCAL - CROSS_BORDER
    */
    'targetSellerTypes'?: Array<string>;
    /**
    * A list of TikTok Shop seller shop codes to allow to register for the campaign. The seller shop code in available in TikTok Shop Seller Central by clicking on the Seller Profile icon in the top right of the user interface. The list must be less than 100 items in length. 
    */
    'targetShopCodes'?: Array<string>;

    static discriminator: string | undefined = undefined;

    static attributeTypeMap: Array<{name: string, baseName: string, type: string}> = [
        {
            "name": "campaignEndTime",
            "baseName": "campaign_end_time",
            "type": "number"
        },
        {
            "name": "campaignStartTime",
            "baseName": "campaign_start_time",
            "type": "number"
        },
        {
            "name": "commissionRate",
            "baseName": "commission_rate",
            "type": "number"
        },
        {
            "name": "contactInfo",
            "baseName": "contact_info",
            "type": "AffiliatePartner202405CreateAffiliatePartnerCampaignRequestBodyContactInfo"
        },
        {
            "name": "description",
            "baseName": "description",
            "type": "string"
        },
        {
            "name": "name",
            "baseName": "name",
            "type": "string"
        },
        {
            "name": "registrationEndTime",
            "baseName": "registration_end_time",
            "type": "number"
        },
        {
            "name": "registrationStartTime",
            "baseName": "registration_start_time",
            "type": "number"
        },
        {
            "name": "targetSellerTypes",
            "baseName": "target_seller_types",
            "type": "Array<string>"
        },
        {
            "name": "targetShopCodes",
            "baseName": "target_shop_codes",
            "type": "Array<string>"
        }    ];

    static getAttributeTypeMap() {
        return AffiliatePartner202405CreateAffiliatePartnerCampaignRequestBody.attributeTypeMap;
    }
}

