/**
 * tiktok shop openapi
 * sdk for apis
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { RequestFile } from '../../models';

export class AffiliatePartner202405EditAffiliatePartnerCampaignRequestBodyContactInfo {
    /**
    * The partner\'s email address.
    */
    'email'?: string;
    /**
    * The partner\'s phone number registered in LINE. Applicable if the target market is TH.
    */
    'line'?: string;
    /**
    * The partner\'s phone number.
    */
    'phone'?: string;
    /**
    * The partner\'s phone number registered in Viber. Applicable if the target market is PH.
    */
    'viber'?: string;
    /**
    * The partner\'s phone number registered in WhatsApp. Applicable if the target market is MY, SG, GB, ID, or US.
    */
    'whatsapp'?: string;
    /**
    * The partner\'s phone number registered in Zalo. Applicable if the target market is VN.
    */
    'zalo'?: string;

    static discriminator: string | undefined = undefined;

    static attributeTypeMap: Array<{name: string, baseName: string, type: string}> = [
        {
            "name": "email",
            "baseName": "email",
            "type": "string"
        },
        {
            "name": "line",
            "baseName": "line",
            "type": "string"
        },
        {
            "name": "phone",
            "baseName": "phone",
            "type": "string"
        },
        {
            "name": "viber",
            "baseName": "viber",
            "type": "string"
        },
        {
            "name": "whatsapp",
            "baseName": "whatsapp",
            "type": "string"
        },
        {
            "name": "zalo",
            "baseName": "zalo",
            "type": "string"
        }    ];

    static getAttributeTypeMap() {
        return AffiliatePartner202405EditAffiliatePartnerCampaignRequestBodyContactInfo.attributeTypeMap;
    }
}

