/**
 * tiktok shop openapi
 * sdk for apis
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { RequestFile } from '../../models';

export class AffiliatePartner202405GenerateAffiliatePartnerCampaignProductLinkResponseData {
    /**
    * A URL for product promotion content. This URL is provided to agencies for sharing with colloborating creators. Creators share this link with followers via the TikTok App. Note that creators control whether or not to add products to their showcase in the pop-up window. 
    */
    'productPromotionLink'?: string;

    static discriminator: string | undefined = undefined;

    static attributeTypeMap: Array<{name: string, baseName: string, type: string}> = [
        {
            "name": "productPromotionLink",
            "baseName": "product_promotion_link",
            "type": "string"
        }    ];

    static getAttributeTypeMap() {
        return AffiliatePartner202405GenerateAffiliatePartnerCampaignProductLinkResponseData.attributeTypeMap;
    }
}

