/**
 * tiktok shop openapi
 * sdk for apis
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { RequestFile } from '../../models';

export class AffiliatePartner202405GenerateAffiliatePartnerCampaignProductLinkRequestBody {
    /**
    * The commission rate paid to a creator in hundredths of a percent (0.01%). The commission rate must be lower than or equal to the total commission rate set by the seller.
    */
    'creatorCommissionRate'?: number;

    static discriminator: string | undefined = undefined;

    static attributeTypeMap: Array<{name: string, baseName: string, type: string}> = [
        {
            "name": "creatorCommissionRate",
            "baseName": "creator_commission_rate",
            "type": "number"
        }    ];

    static getAttributeTypeMap() {
        return AffiliatePartner202405GenerateAffiliatePartnerCampaignProductLinkRequestBody.attributeTypeMap;
    }
}

