/**
 * tiktok shop openapi
 * sdk for apis
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { RequestFile } from '../../models';

export class AffiliatePartner202405GetAffiliatePartnerCampaignProductListResponseDataProductsSkuInformationListBasePrice {
    /**
    * The currency of the SKU price. Possible values based on the region: - BRL:  Brazil - EUR: France, Germany, Ireland, Italy, Spain - GBP: United Kingdom - IDR: Indonesia - JPY: Japan - MXN: Mexico - MYR: Malaysia - PHP: Philippines - SGD: Singapore - THB: Thailand - USD: United States - VND: Vietnam
    */
    'currency'?: string;
    /**
    * The SKU\'s list price information that has been verified to be legitimate by the audit team. This is equivalent to the manufacturer\'s suggested retail price (MSRP), or the recommended retail price (RRP).
    */
    'listPrice'?: string;
    /**
    * localized dutiable price 
    */
    'localizedDutiablePrice'?: string;
    /**
    * the region code of the sku
    */
    'regionCode'?: string;
    /**
    * The SKU\'s selling price, inclusive of tax. Applicable only for cross-border sellers from China.
    */
    'salePrice'?: string;

    static discriminator: string | undefined = undefined;

    static attributeTypeMap: Array<{name: string, baseName: string, type: string}> = [
        {
            "name": "currency",
            "baseName": "currency",
            "type": "string"
        },
        {
            "name": "listPrice",
            "baseName": "list_price",
            "type": "string"
        },
        {
            "name": "localizedDutiablePrice",
            "baseName": "localized_dutiable_price",
            "type": "string"
        },
        {
            "name": "regionCode",
            "baseName": "region_code",
            "type": "string"
        },
        {
            "name": "salePrice",
            "baseName": "sale_price",
            "type": "string"
        }    ];

    static getAttributeTypeMap() {
        return AffiliatePartner202405GetAffiliatePartnerCampaignProductListResponseDataProductsSkuInformationListBasePrice.attributeTypeMap;
    }
}

