/**
 * tiktok shop openapi
 * sdk for apis
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { RequestFile } from '../../models';
import { AffiliatePartner202405GetAffiliatePartnerCampaignProductListResponseDataProductsCategory } from './GetAffiliatePartnerCampaignProductListResponseDataProductsCategory';
import { AffiliatePartner202405GetAffiliatePartnerCampaignProductListResponseDataProductsHighestPrice } from './GetAffiliatePartnerCampaignProductListResponseDataProductsHighestPrice';
import { AffiliatePartner202405GetAffiliatePartnerCampaignProductListResponseDataProductsLowestPrice } from './GetAffiliatePartnerCampaignProductListResponseDataProductsLowestPrice';
import { AffiliatePartner202405GetAffiliatePartnerCampaignProductListResponseDataProductsSkuInformationList } from './GetAffiliatePartnerCampaignProductListResponseDataProductsSkuInformationList';

export class AffiliatePartner202405GetAffiliatePartnerCampaignProductListResponseDataProducts {
    'category'?: AffiliatePartner202405GetAffiliatePartnerCampaignProductListResponseDataProductsCategory;
    /**
    * The creator commission rate in hundredths of a percent (0.01%) units.
    */
    'creatorCommissionRate'?: number;
    'highestPrice'?: AffiliatePartner202405GetAffiliatePartnerCampaignProductListResponseDataProductsHighestPrice;
    /**
    * The product identifier.
    */
    'id'?: string;
    /**
    * The number of in-stock units of all SKUs for this product.
    */
    'inventory'?: number;
    /**
    * Set to `true` if a product URL is available. Set to `false` if no product URL is available.
    */
    'isAvailable'?: boolean;
    'lowestPrice'?: AffiliatePartner202405GetAffiliatePartnerCampaignProductListResponseDataProductsLowestPrice;
    /**
    * The product image URL.
    */
    'mainImageUrl'?: string;
    /**
    * The product name.
    */
    'name'?: string;
    /**
    * The product open collaboration commission rate in hundredths of a percent (0.01%) units.  
    */
    'openCollaborationCommissionRate'?: number;
    /**
    * The partner commission rate in hundredths of a percent (0.01%) units.
    */
    'partnerCommissionRate'?: number;
    /**
    * Return product description
    */
    'productDescription'?: string;
    /**
    * The total number of units sold of this product for this campaign.
    */
    'productSales'?: number;
    /**
    * The product review status. This an enumerated type with values: - PENDING - APPROVED - REJECTED - PENDING_CLOSED - CLOSED
    */
    'reviewStatus'?: string;
    /**
    * The total amount of sample inventory available for allocation to creators by the seller.
    */
    'sampleQuota'?: number;
    /**
    * The TikTok Shop name.
    */
    'shopName'?: string;
    /**
    * A list of Stock Keeping Units (SKUs) used to identify distinct variants of the product.
    */
    'skuInformationList'?: Array<AffiliatePartner202405GetAffiliatePartnerCampaignProductListResponseDataProductsSkuInformationList>;
    /**
    * The total commission rate in hundredths of a percent (0.01%) units.
    */
    'totalCommissionRate'?: number;

    static discriminator: string | undefined = undefined;

    static attributeTypeMap: Array<{name: string, baseName: string, type: string}> = [
        {
            "name": "category",
            "baseName": "category",
            "type": "AffiliatePartner202405GetAffiliatePartnerCampaignProductListResponseDataProductsCategory"
        },
        {
            "name": "creatorCommissionRate",
            "baseName": "creator_commission_rate",
            "type": "number"
        },
        {
            "name": "highestPrice",
            "baseName": "highest_price",
            "type": "AffiliatePartner202405GetAffiliatePartnerCampaignProductListResponseDataProductsHighestPrice"
        },
        {
            "name": "id",
            "baseName": "id",
            "type": "string"
        },
        {
            "name": "inventory",
            "baseName": "inventory",
            "type": "number"
        },
        {
            "name": "isAvailable",
            "baseName": "is_available",
            "type": "boolean"
        },
        {
            "name": "lowestPrice",
            "baseName": "lowest_price",
            "type": "AffiliatePartner202405GetAffiliatePartnerCampaignProductListResponseDataProductsLowestPrice"
        },
        {
            "name": "mainImageUrl",
            "baseName": "main_image_url",
            "type": "string"
        },
        {
            "name": "name",
            "baseName": "name",
            "type": "string"
        },
        {
            "name": "openCollaborationCommissionRate",
            "baseName": "open_collaboration_commission_rate",
            "type": "number"
        },
        {
            "name": "partnerCommissionRate",
            "baseName": "partner_commission_rate",
            "type": "number"
        },
        {
            "name": "productDescription",
            "baseName": "product_description",
            "type": "string"
        },
        {
            "name": "productSales",
            "baseName": "product_sales",
            "type": "number"
        },
        {
            "name": "reviewStatus",
            "baseName": "review_status",
            "type": "string"
        },
        {
            "name": "sampleQuota",
            "baseName": "sample_quota",
            "type": "number"
        },
        {
            "name": "shopName",
            "baseName": "shop_name",
            "type": "string"
        },
        {
            "name": "skuInformationList",
            "baseName": "sku_information_list",
            "type": "Array<AffiliatePartner202405GetAffiliatePartnerCampaignProductListResponseDataProductsSkuInformationList>"
        },
        {
            "name": "totalCommissionRate",
            "baseName": "total_commission_rate",
            "type": "number"
        }    ];

    static getAttributeTypeMap() {
        return AffiliatePartner202405GetAffiliatePartnerCampaignProductListResponseDataProducts.attributeTypeMap;
    }
}

