/**
 * tiktok shop openapi
 * sdk for apis
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { RequestFile } from '../../models';
import { AffiliatePartner202405GetAffiliatePartnerCampaignProductListResponseDataProducts } from './GetAffiliatePartnerCampaignProductListResponseDataProducts';

export class AffiliatePartner202405GetAffiliatePartnerCampaignProductListResponseData {
    /**
    * An opaque token used to retrieve the next page of a paginated result set.
    */
    'nextPageToken'?: string;
    /**
    * The list of products.
    */
    'products'?: Array<AffiliatePartner202405GetAffiliatePartnerCampaignProductListResponseDataProducts>;
    /**
    * The total number of products in the list.
    */
    'totalCount'?: number;

    static discriminator: string | undefined = undefined;

    static attributeTypeMap: Array<{name: string, baseName: string, type: string}> = [
        {
            "name": "nextPageToken",
            "baseName": "next_page_token",
            "type": "string"
        },
        {
            "name": "products",
            "baseName": "products",
            "type": "Array<AffiliatePartner202405GetAffiliatePartnerCampaignProductListResponseDataProducts>"
        },
        {
            "name": "totalCount",
            "baseName": "total_count",
            "type": "number"
        }    ];

    static getAttributeTypeMap() {
        return AffiliatePartner202405GetAffiliatePartnerCampaignProductListResponseData.attributeTypeMap;
    }
}

