/**
 * tiktok shop openapi
 * sdk for apis
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { RequestFile } from '../../models';

export class AffiliatePartner202405GetAffiliatePartnerCampaignListResponseDataCampaigns {
    /**
    * The scheduled end time in Unix epoch time format for the campaign. Note that the end time must be less than 360 days from the start date. This field is no longer editable when the campaign status is set to `CLOSED`.
    */
    'campaignEndTime'?: number;
    /**
    * The scheduled start time in Unix epoch time format for the campaign. Note that this field can be updated when the campaign status is set to `READY` or `UPCOMING` only.
    */
    'campaignStartTime'?: number;
    /**
    * The campaign identifier.
    */
    'id'?: string;
    /**
    * The campaign name.
    */
    'name'?: string;
    /**
    * The scheduled end time in Unix epoch time format for seller product registration. This field is no longer editable when the campaign status is set to `CLOSED`.
    */
    'registrationEndTime'?: number;
    /**
    * The scheduled start time in Unix epoch format for seller product registration. Note that this field can be updated when the campaign status is set to `READY` or `UPCOMING` only.
    */
    'registrationStartTime'?: number;
    /**
    * The campaign status. The status is an enumerated type with values: - READY - UPCOMING - ONGOING - CLOSED
    */
    'status'?: string;

    static discriminator: string | undefined = undefined;

    static attributeTypeMap: Array<{name: string, baseName: string, type: string}> = [
        {
            "name": "campaignEndTime",
            "baseName": "campaign_end_time",
            "type": "number"
        },
        {
            "name": "campaignStartTime",
            "baseName": "campaign_start_time",
            "type": "number"
        },
        {
            "name": "id",
            "baseName": "id",
            "type": "string"
        },
        {
            "name": "name",
            "baseName": "name",
            "type": "string"
        },
        {
            "name": "registrationEndTime",
            "baseName": "registration_end_time",
            "type": "number"
        },
        {
            "name": "registrationStartTime",
            "baseName": "registration_start_time",
            "type": "number"
        },
        {
            "name": "status",
            "baseName": "status",
            "type": "string"
        }    ];

    static getAttributeTypeMap() {
        return AffiliatePartner202405GetAffiliatePartnerCampaignListResponseDataCampaigns.attributeTypeMap;
    }
}

