/**
 * tiktok shop openapi
 * sdk for apis
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { RequestFile } from '../../models';
import { AffiliatePartner202405GetAffiliatePartnerCampaignProductListResponseDataProductsSkuInformationListBasePrice } from './GetAffiliatePartnerCampaignProductListResponseDataProductsSkuInformationListBasePrice';
import { AffiliatePartner202405GetAffiliatePartnerCampaignProductListResponseDataProductsSkuInformationListInventory } from './GetAffiliatePartnerCampaignProductListResponseDataProductsSkuInformationListInventory';
import { AffiliatePartner202405GetAffiliatePartnerCampaignProductListResponseDataProductsSkuInformationListProperties } from './GetAffiliatePartnerCampaignProductListResponseDataProductsSkuInformationListProperties';
import { AffiliatePartner202405GetAffiliatePartnerCampaignProductListResponseDataProductsSkuInformationListRegionPrices } from './GetAffiliatePartnerCampaignProductListResponseDataProductsSkuInformationListRegionPrices';

export class AffiliatePartner202405GetAffiliatePartnerCampaignProductListResponseDataProductsSkuInformationList {
    'basePrice'?: AffiliatePartner202405GetAffiliatePartnerCampaignProductListResponseDataProductsSkuInformationListBasePrice;
    'inventory'?: AffiliatePartner202405GetAffiliatePartnerCampaignProductListResponseDataProductsSkuInformationListInventory;
    /**
    * The properties of the sku
    */
    'properties'?: Array<AffiliatePartner202405GetAffiliatePartnerCampaignProductListResponseDataProductsSkuInformationListProperties>;
    /**
    * region prices
    */
    'regionPrices'?: Array<AffiliatePartner202405GetAffiliatePartnerCampaignProductListResponseDataProductsSkuInformationListRegionPrices>;
    /**
    * The id of the sku
    */
    'skuId'?: string;
    /**
    * The name of the sku
    */
    'skuName'?: string;

    static discriminator: string | undefined = undefined;

    static attributeTypeMap: Array<{name: string, baseName: string, type: string}> = [
        {
            "name": "basePrice",
            "baseName": "base_price",
            "type": "AffiliatePartner202405GetAffiliatePartnerCampaignProductListResponseDataProductsSkuInformationListBasePrice"
        },
        {
            "name": "inventory",
            "baseName": "inventory",
            "type": "AffiliatePartner202405GetAffiliatePartnerCampaignProductListResponseDataProductsSkuInformationListInventory"
        },
        {
            "name": "properties",
            "baseName": "properties",
            "type": "Array<AffiliatePartner202405GetAffiliatePartnerCampaignProductListResponseDataProductsSkuInformationListProperties>"
        },
        {
            "name": "regionPrices",
            "baseName": "region_prices",
            "type": "Array<AffiliatePartner202405GetAffiliatePartnerCampaignProductListResponseDataProductsSkuInformationListRegionPrices>"
        },
        {
            "name": "skuId",
            "baseName": "sku_id",
            "type": "string"
        },
        {
            "name": "skuName",
            "baseName": "sku_name",
            "type": "string"
        }    ];

    static getAttributeTypeMap() {
        return AffiliatePartner202405GetAffiliatePartnerCampaignProductListResponseDataProductsSkuInformationList.attributeTypeMap;
    }
}

