/**
 * tiktok shop openapi
 * sdk for apis
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { RequestFile } from '../../models';

export class AffiliatePartner202405ReviewAffiliatePartnerCampaignProductRequestBody {
    /**
    * If the `review_result` property is set to `REJECT` or `REJECT_FOREVER`, this property is set to the enumerated reason that the TikTok Affiliate Partner rejected the product. This is an enumerated type with values: - COMMISSION_TOO_LOW - PRODUCT_HARD_TO_PROMOTE - PRODUCT_TOO_EXPENSIVE - NO_SUITABLE_CREATOR
    */
    'rejectReasons'?: Array<string>;
    /**
    * The product review decision by the TikTok Affiliate Partner. This is an enumerated type with values: - APPROVE - REJECT - REJECT_FOREVER
    */
    'reviewResult'?: string;

    static discriminator: string | undefined = undefined;

    static attributeTypeMap: Array<{name: string, baseName: string, type: string}> = [
        {
            "name": "rejectReasons",
            "baseName": "reject_reasons",
            "type": "Array<string>"
        },
        {
            "name": "reviewResult",
            "baseName": "review_result",
            "type": "string"
        }    ];

    static getAttributeTypeMap() {
        return AffiliatePartner202405ReviewAffiliatePartnerCampaignProductRequestBody.attributeTypeMap;
    }
}

