/**
 * tiktok shop openapi
 * sdk for apis
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { RequestFile } from '../../models';
import { AffiliatePartner202505PartnerGenerateMultiAffiliateCampaignProductLinkResponseDataProductPromotionLinks } from './PartnerGenerateMultiAffiliateCampaignProductLinkResponseDataProductPromotionLinks';

export class AffiliatePartner202505PartnerGenerateMultiAffiliateCampaignProductLinkResponseData {
    /**
    * The list of products for which the promotion links failed to be generated.
    */
    'failedProductIds'?: Array<string>;
    /**
    * The list of products for which the promotion links are generated successfully.
    */
    'productPromotionLinks'?: Array<AffiliatePartner202505PartnerGenerateMultiAffiliateCampaignProductLinkResponseDataProductPromotionLinks>;

    static discriminator: string | undefined = undefined;

    static attributeTypeMap: Array<{name: string, baseName: string, type: string}> = [
        {
            "name": "failedProductIds",
            "baseName": "failed_product_ids",
            "type": "Array<string>"
        },
        {
            "name": "productPromotionLinks",
            "baseName": "product_promotion_links",
            "type": "Array<AffiliatePartner202505PartnerGenerateMultiAffiliateCampaignProductLinkResponseDataProductPromotionLinks>"
        }    ];

    static getAttributeTypeMap() {
        return AffiliatePartner202505PartnerGenerateMultiAffiliateCampaignProductLinkResponseData.attributeTypeMap;
    }
}

