/**
 * tiktok shop openapi
 * sdk for apis
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { RequestFile } from '../../models';

export class AffiliatePartner202505PartnerGenerateMultiAffiliateCampaignProductLinkResponseDataProductPromotionLinks {
    /**
    * This is the product promotion link that agencies can share with collaborated creators. Creators can copy/paste this link into the web browser. Creators will be re-directed to the add-product-link page in the Tikotk app. Creators can decide whether to add products to their showcases in the pop-up window.
    */
    'link'?: string;
    /**
    * The ID of the product to promote.
    */
    'productId'?: string;

    static discriminator: string | undefined = undefined;

    static attributeTypeMap: Array<{name: string, baseName: string, type: string}> = [
        {
            "name": "link",
            "baseName": "link",
            "type": "string"
        },
        {
            "name": "productId",
            "baseName": "product_id",
            "type": "string"
        }    ];

    static getAttributeTypeMap() {
        return AffiliatePartner202505PartnerGenerateMultiAffiliateCampaignProductLinkResponseDataProductPromotionLinks.attributeTypeMap;
    }
}

