/**
 * tiktok shop openapi
 * sdk for apis
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { RequestFile } from '../../models';

export class AffiliatePartner202505PartnerGenerateMultiAffiliateCampaignProductLinkRequestBody {
    /**
    * The list of product IDs. The max length is 50.
    */
    'productIds'?: Array<string>;

    static discriminator: string | undefined = undefined;

    static attributeTypeMap: Array<{name: string, baseName: string, type: string}> = [
        {
            "name": "productIds",
            "baseName": "product_ids",
            "type": "Array<string>"
        }    ];

    static getAttributeTypeMap() {
        return AffiliatePartner202505PartnerGenerateMultiAffiliateCampaignProductLinkRequestBody.attributeTypeMap;
    }
}

