import { Order202507GetOrderDetailResponseDataOrdersHandlingDuration } from './GetOrderDetailResponseDataOrdersHandlingDuration';
import { Order202507GetOrderDetailResponseDataOrdersLineItems } from './GetOrderDetailResponseDataOrdersLineItems';
import { Order202507GetOrderDetailResponseDataOrdersPackages } from './GetOrderDetailResponseDataOrdersPackages';
import { Order202507GetOrderDetailResponseDataOrdersPayment } from './GetOrderDetailResponseDataOrdersPayment';
import { Order202507GetOrderDetailResponseDataOrdersRecipientAddress } from './GetOrderDetailResponseDataOrdersRecipientAddress';
export declare class Order202507GetOrderDetailResponseDataOrders {
    'autoCombineGroupId'?: string;
    'buyerEmail'?: string;
    'buyerMessage'?: string;
    'cancelOrderSlaTime'?: number;
    'cancelReason'?: string;
    'cancelTime'?: number;
    'cancellationInitiator'?: string;
    'channelEntityNationalRegistryId'?: string;
    'collectionDueTime'?: number;
    'collectionTime'?: number;
    'commercePlatform'?: string;
    'consultationId'?: string;
    'cpf'?: string;
    'cpfName'?: string;
    'createTime'?: number;
    'deliveryDueTime'?: number;
    'deliveryOptionId'?: string;
    'deliveryOptionName'?: string;
    'deliveryOptionRequiredDeliveryTime'?: number;
    'deliverySlaTime'?: number;
    'deliveryTime'?: number;
    'deliveryType'?: string;
    'exchangeSourceOrderId'?: string;
    'fastDeliveryProgram'?: string;
    'fastDispatchSlaTime'?: number;
    'fulfillmentType'?: string;
    'handlingDuration'?: Order202507GetOrderDetailResponseDataOrdersHandlingDuration;
    'hasUpdatedRecipientAddress'?: boolean;
    'id'?: string;
    'isBuyerRequestCancel'?: boolean;
    'isCod'?: boolean;
    'isExchangeOrder'?: boolean;
    'isOnHoldOrder'?: boolean;
    'isReplacementOrder'?: boolean;
    'isSampleOrder'?: boolean;
    'lineItems'?: Array<Order202507GetOrderDetailResponseDataOrdersLineItems>;
    'needUploadInvoice'?: string;
    'orderType'?: string;
    'packages'?: Array<Order202507GetOrderDetailResponseDataOrdersPackages>;
    'paidTime'?: number;
    'payment'?: Order202507GetOrderDetailResponseDataOrdersPayment;
    'paymentAuthCode'?: string;
    'paymentCardType'?: string;
    'paymentMethodCode'?: string;
    'paymentMethodName'?: string;
    'pickUpCutOffTime'?: number;
    'recipientAddress'?: Order202507GetOrderDetailResponseDataOrdersRecipientAddress;
    'releaseDate'?: number;
    'replacedOrderId'?: string;
    'requestCancelTime'?: number;
    'rtsSlaTime'?: number;
    'rtsTime'?: number;
    'sellerNote'?: string;
    'shippingDueTime'?: number;
    'shippingProvider'?: string;
    'shippingProviderId'?: string;
    'shippingType'?: string;
    'splitOrCombineTag'?: string;
    'status'?: string;
    'trackingNumber'?: string;
    'ttsSlaTime'?: number;
    'updateTime'?: number;
    'userId'?: string;
    'warehouseId'?: string;
    static discriminator: string | undefined;
    static attributeTypeMap: Array<{
        name: string;
        baseName: string;
        type: string;
    }>;
    static getAttributeTypeMap(): {
        name: string;
        baseName: string;
        type: string;
    }[];
}
//# sourceMappingURL=GetOrderDetailResponseDataOrders.d.ts.map