import { AffiliateSeller202406GetMarketplaceCreatorPerformanceResponseDataCreatorAvatar } from './GetMarketplaceCreatorPerformanceResponseDataCreatorAvatar';
import { AffiliateSeller202406GetMarketplaceCreatorPerformanceResponseDataCreatorAvgCommissionRateRange } from './GetMarketplaceCreatorPerformanceResponseDataCreatorAvgCommissionRateRange';
import { AffiliateSeller202406GetMarketplaceCreatorPerformanceResponseDataCreatorAvgGmvPerBuyer } from './GetMarketplaceCreatorPerformanceResponseDataCreatorAvgGmvPerBuyer';
import { AffiliateSeller202406GetMarketplaceCreatorPerformanceResponseDataCreatorAvgGmvPerBuyerRange } from './GetMarketplaceCreatorPerformanceResponseDataCreatorAvgGmvPerBuyerRange';
import { AffiliateSeller202406GetMarketplaceCreatorPerformanceResponseDataCreatorCategoryGmvDistribution } from './GetMarketplaceCreatorPerformanceResponseDataCreatorCategoryGmvDistribution';
import { AffiliateSeller202406GetMarketplaceCreatorPerformanceResponseDataCreatorContentGmvDistribution } from './GetMarketplaceCreatorPerformanceResponseDataCreatorContentGmvDistribution';
import { AffiliateSeller202406GetMarketplaceCreatorPerformanceResponseDataCreatorGmv } from './GetMarketplaceCreatorPerformanceResponseDataCreatorGmv';
import { AffiliateSeller202406GetMarketplaceCreatorPerformanceResponseDataCreatorGmvRange } from './GetMarketplaceCreatorPerformanceResponseDataCreatorGmvRange';
import { AffiliateSeller202406GetMarketplaceCreatorPerformanceResponseDataCreatorGpm } from './GetMarketplaceCreatorPerformanceResponseDataCreatorGpm';
import { AffiliateSeller202406GetMarketplaceCreatorPerformanceResponseDataCreatorGpmRange } from './GetMarketplaceCreatorPerformanceResponseDataCreatorGpmRange';
import { AffiliateSeller202406GetMarketplaceCreatorPerformanceResponseDataCreatorLiveGmv } from './GetMarketplaceCreatorPerformanceResponseDataCreatorLiveGmv';
import { AffiliateSeller202406GetMarketplaceCreatorPerformanceResponseDataCreatorLiveGpm } from './GetMarketplaceCreatorPerformanceResponseDataCreatorLiveGpm';
import { AffiliateSeller202406GetMarketplaceCreatorPerformanceResponseDataCreatorLiveGpmRange } from './GetMarketplaceCreatorPerformanceResponseDataCreatorLiveGpmRange';
import { AffiliateSeller202406GetMarketplaceCreatorPerformanceResponseDataCreatorProductOriginalPriceRange } from './GetMarketplaceCreatorPerformanceResponseDataCreatorProductOriginalPriceRange';
import { AffiliateSeller202406GetMarketplaceCreatorPerformanceResponseDataCreatorUnitsSoldRange } from './GetMarketplaceCreatorPerformanceResponseDataCreatorUnitsSoldRange';
import { AffiliateSeller202406GetMarketplaceCreatorPerformanceResponseDataCreatorVideoGmv } from './GetMarketplaceCreatorPerformanceResponseDataCreatorVideoGmv';
import { AffiliateSeller202406GetMarketplaceCreatorPerformanceResponseDataCreatorVideoGpm } from './GetMarketplaceCreatorPerformanceResponseDataCreatorVideoGpm';
import { AffiliateSeller202406GetMarketplaceCreatorPerformanceResponseDataCreatorVideoGpmRange } from './GetMarketplaceCreatorPerformanceResponseDataCreatorVideoGpmRange';
export declare class AffiliateSeller202406GetMarketplaceCreatorPerformanceResponseDataCreator {
    'avatar'?: AffiliateSeller202406GetMarketplaceCreatorPerformanceResponseDataCreatorAvatar;
    'avgCommissionRate'?: number;
    'avgCommissionRateRange'?: AffiliateSeller202406GetMarketplaceCreatorPerformanceResponseDataCreatorAvgCommissionRateRange;
    'avgEcLiveCommentCount'?: number;
    'avgEcLiveLikeCount'?: number;
    'avgEcLiveShareCount'?: number;
    'avgEcLiveViewCount'?: number;
    'avgEcVideoCommentCount'?: number;
    'avgEcVideoLikeCount'?: number;
    'avgEcVideoPlayCount'?: number;
    'avgEcVideoShareCount'?: number;
    'avgGmvPerBuyer'?: AffiliateSeller202406GetMarketplaceCreatorPerformanceResponseDataCreatorAvgGmvPerBuyer;
    'avgGmvPerBuyerRange'?: AffiliateSeller202406GetMarketplaceCreatorPerformanceResponseDataCreatorAvgGmvPerBuyerRange;
    'bioDescription'?: string;
    'brandCollaborationCount'?: number;
    'categoryGmvDistribution'?: Array<AffiliateSeller202406GetMarketplaceCreatorPerformanceResponseDataCreatorCategoryGmvDistribution>;
    'categoryIds'?: Array<string>;
    'contentGmvDistribution'?: Array<AffiliateSeller202406GetMarketplaceCreatorPerformanceResponseDataCreatorContentGmvDistribution>;
    'ecLiveCount'?: number;
    'ecLiveEngagementRate'?: string;
    'ecVideoCount'?: number;
    'followerCount'?: number;
    'gmv'?: AffiliateSeller202406GetMarketplaceCreatorPerformanceResponseDataCreatorGmv;
    'gmvRange'?: AffiliateSeller202406GetMarketplaceCreatorPerformanceResponseDataCreatorGmvRange;
    'gpm'?: AffiliateSeller202406GetMarketplaceCreatorPerformanceResponseDataCreatorGpm;
    'gpmRange'?: AffiliateSeller202406GetMarketplaceCreatorPerformanceResponseDataCreatorGpmRange;
    'liveGmv'?: AffiliateSeller202406GetMarketplaceCreatorPerformanceResponseDataCreatorLiveGmv;
    'liveGpm'?: AffiliateSeller202406GetMarketplaceCreatorPerformanceResponseDataCreatorLiveGpm;
    'liveGpmRange'?: AffiliateSeller202406GetMarketplaceCreatorPerformanceResponseDataCreatorLiveGpmRange;
    'nickname'?: string;
    'productOriginalPriceRange'?: AffiliateSeller202406GetMarketplaceCreatorPerformanceResponseDataCreatorProductOriginalPriceRange;
    'profileTtUri'?: string;
    'promotedProductNum'?: number;
    'selectionRegion'?: string;
    'topCollaboratedBrandIds'?: Array<string>;
    'unitsSold'?: number;
    'unitsSoldRange'?: AffiliateSeller202406GetMarketplaceCreatorPerformanceResponseDataCreatorUnitsSoldRange;
    'username'?: string;
    'videoGmv'?: AffiliateSeller202406GetMarketplaceCreatorPerformanceResponseDataCreatorVideoGmv;
    'videoGpm'?: AffiliateSeller202406GetMarketplaceCreatorPerformanceResponseDataCreatorVideoGpm;
    'videoGpmRange'?: AffiliateSeller202406GetMarketplaceCreatorPerformanceResponseDataCreatorVideoGpmRange;
    static discriminator: string | undefined;
    static attributeTypeMap: Array<{
        name: string;
        baseName: string;
        type: string;
    }>;
    static getAttributeTypeMap(): {
        name: string;
        baseName: string;
        type: string;
    }[];
}
//# sourceMappingURL=GetMarketplaceCreatorPerformanceResponseDataCreator.d.ts.map