/**
 * tiktok shop openapi
 * sdk for apis
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { RequestFile } from '../../models';
import { Authorization202405GetAuthorizedCategoryAssetsResponseDataCategoryAssets } from './GetAuthorizedCategoryAssetsResponseDataCategoryAssets';

export class Authorization202405GetAuthorizedCategoryAssetsResponseData {
    /**
    * The list of business category assets that a partner has authorized for the app.
    */
    'categoryAssets'?: Array<Authorization202405GetAuthorizedCategoryAssetsResponseDataCategoryAssets>;

    static discriminator: string | undefined = undefined;

    static attributeTypeMap: Array<{name: string, baseName: string, type: string}> = [
        {
            "name": "categoryAssets",
            "baseName": "category_assets",
            "type": "Array<Authorization202405GetAuthorizedCategoryAssetsResponseDataCategoryAssets>"
        }    ];

    static getAttributeTypeMap() {
        return Authorization202405GetAuthorizedCategoryAssetsResponseData.attributeTypeMap;
    }
}

