/**
 * tiktok shop openapi
 * sdk for apis
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { RequestFile } from '../../models';
import { Affiliate202309GetShopProductsResponseDataProductsImages } from './GetShopProductsResponseDataProductsImages';
import { Affiliate202309GetShopProductsResponseDataProductsPrice } from './GetShopProductsResponseDataProductsPrice';

export class Affiliate202309GetShopProductsResponseDataProducts {
    /**
    * Showcase add status with possible values: - ADDABLE - ADDED - REJECTED
    */
    'addedStatus'?: string;
    /**
    * The brand name a seller has set for a product.
    */
    'brandName'?: string;
    /**
    * TikTok product ID.
    */
    'id'?: string;
    /**
    * Images of a product.
    */
    'images'?: Array<Affiliate202309GetShopProductsResponseDataProductsImages>;
    'price'?: Affiliate202309GetShopProductsResponseDataProductsPrice;
    /**
    * The number of products that have been sold.
    */
    'salesCount'?: number;
    /**
    * Product name.
    */
    'title'?: string;

    static discriminator: string | undefined = undefined;

    static attributeTypeMap: Array<{name: string, baseName: string, type: string}> = [
        {
            "name": "addedStatus",
            "baseName": "added_status",
            "type": "string"
        },
        {
            "name": "brandName",
            "baseName": "brand_name",
            "type": "string"
        },
        {
            "name": "id",
            "baseName": "id",
            "type": "string"
        },
        {
            "name": "images",
            "baseName": "images",
            "type": "Array<Affiliate202309GetShopProductsResponseDataProductsImages>"
        },
        {
            "name": "price",
            "baseName": "price",
            "type": "Affiliate202309GetShopProductsResponseDataProductsPrice"
        },
        {
            "name": "salesCount",
            "baseName": "sales_count",
            "type": "number"
        },
        {
            "name": "title",
            "baseName": "title",
            "type": "string"
        }    ];

    static getAttributeTypeMap() {
        return Affiliate202309GetShopProductsResponseDataProducts.attributeTypeMap;
    }
}

