import { AffiliateSeller202505GetMarketplaceCreatorPerformanceResponseDataCreatorAvatar } from './GetMarketplaceCreatorPerformanceResponseDataCreatorAvatar';
import { AffiliateSeller202505GetMarketplaceCreatorPerformanceResponseDataCreatorAvgCommissionRateRange } from './GetMarketplaceCreatorPerformanceResponseDataCreatorAvgCommissionRateRange';
import { AffiliateSeller202505GetMarketplaceCreatorPerformanceResponseDataCreatorAvgGmvPerBuyer } from './GetMarketplaceCreatorPerformanceResponseDataCreatorAvgGmvPerBuyer';
import { AffiliateSeller202505GetMarketplaceCreatorPerformanceResponseDataCreatorAvgGmvPerBuyerRange } from './GetMarketplaceCreatorPerformanceResponseDataCreatorAvgGmvPerBuyerRange';
import { AffiliateSeller202505GetMarketplaceCreatorPerformanceResponseDataCreatorCategoryGmvDistribution } from './GetMarketplaceCreatorPerformanceResponseDataCreatorCategoryGmvDistribution';
import { AffiliateSeller202505GetMarketplaceCreatorPerformanceResponseDataCreatorContentGmvDistribution } from './GetMarketplaceCreatorPerformanceResponseDataCreatorContentGmvDistribution';
import { AffiliateSeller202505GetMarketplaceCreatorPerformanceResponseDataCreatorGmv } from './GetMarketplaceCreatorPerformanceResponseDataCreatorGmv';
import { AffiliateSeller202505GetMarketplaceCreatorPerformanceResponseDataCreatorGmvRange } from './GetMarketplaceCreatorPerformanceResponseDataCreatorGmvRange';
import { AffiliateSeller202505GetMarketplaceCreatorPerformanceResponseDataCreatorGpm } from './GetMarketplaceCreatorPerformanceResponseDataCreatorGpm';
import { AffiliateSeller202505GetMarketplaceCreatorPerformanceResponseDataCreatorGpmRange } from './GetMarketplaceCreatorPerformanceResponseDataCreatorGpmRange';
import { AffiliateSeller202505GetMarketplaceCreatorPerformanceResponseDataCreatorLiveGmv } from './GetMarketplaceCreatorPerformanceResponseDataCreatorLiveGmv';
import { AffiliateSeller202505GetMarketplaceCreatorPerformanceResponseDataCreatorLiveGpm } from './GetMarketplaceCreatorPerformanceResponseDataCreatorLiveGpm';
import { AffiliateSeller202505GetMarketplaceCreatorPerformanceResponseDataCreatorLiveGpmRange } from './GetMarketplaceCreatorPerformanceResponseDataCreatorLiveGpmRange';
import { AffiliateSeller202505GetMarketplaceCreatorPerformanceResponseDataCreatorProductOriginalPriceRange } from './GetMarketplaceCreatorPerformanceResponseDataCreatorProductOriginalPriceRange';
import { AffiliateSeller202505GetMarketplaceCreatorPerformanceResponseDataCreatorUnitsSoldRange } from './GetMarketplaceCreatorPerformanceResponseDataCreatorUnitsSoldRange';
import { AffiliateSeller202505GetMarketplaceCreatorPerformanceResponseDataCreatorVideoGmv } from './GetMarketplaceCreatorPerformanceResponseDataCreatorVideoGmv';
import { AffiliateSeller202505GetMarketplaceCreatorPerformanceResponseDataCreatorVideoGpm } from './GetMarketplaceCreatorPerformanceResponseDataCreatorVideoGpm';
import { AffiliateSeller202505GetMarketplaceCreatorPerformanceResponseDataCreatorVideoGpmRange } from './GetMarketplaceCreatorPerformanceResponseDataCreatorVideoGpmRange';
export declare class AffiliateSeller202505GetMarketplaceCreatorPerformanceResponseDataCreator {
    'avatar'?: AffiliateSeller202505GetMarketplaceCreatorPerformanceResponseDataCreatorAvatar;
    'avgCommissionRate'?: number;
    'avgCommissionRateRange'?: AffiliateSeller202505GetMarketplaceCreatorPerformanceResponseDataCreatorAvgCommissionRateRange;
    'avgEcLiveCommentCount'?: number;
    'avgEcLiveLikeCount'?: number;
    'avgEcLiveShareCount'?: number;
    'avgEcLiveViewCount'?: number;
    'avgEcVideoCommentCount'?: number;
    'avgEcVideoLikeCount'?: number;
    'avgEcVideoPlayCount'?: number;
    'avgEcVideoShareCount'?: number;
    'avgGmvPerBuyer'?: AffiliateSeller202505GetMarketplaceCreatorPerformanceResponseDataCreatorAvgGmvPerBuyer;
    'avgGmvPerBuyerRange'?: AffiliateSeller202505GetMarketplaceCreatorPerformanceResponseDataCreatorAvgGmvPerBuyerRange;
    'bioDescription'?: string;
    'brandCollaborationCount'?: number;
    'categoryGmvDistribution'?: Array<AffiliateSeller202505GetMarketplaceCreatorPerformanceResponseDataCreatorCategoryGmvDistribution>;
    'categoryIds'?: Array<string>;
    'contentGmvDistribution'?: Array<AffiliateSeller202505GetMarketplaceCreatorPerformanceResponseDataCreatorContentGmvDistribution>;
    'ecLiveCount'?: number;
    'ecLiveEngagementRate'?: string;
    'ecVideoCount'?: number;
    'followerCount'?: number;
    'gmv'?: AffiliateSeller202505GetMarketplaceCreatorPerformanceResponseDataCreatorGmv;
    'gmvRange'?: AffiliateSeller202505GetMarketplaceCreatorPerformanceResponseDataCreatorGmvRange;
    'gpm'?: AffiliateSeller202505GetMarketplaceCreatorPerformanceResponseDataCreatorGpm;
    'gpmRange'?: AffiliateSeller202505GetMarketplaceCreatorPerformanceResponseDataCreatorGpmRange;
    'liveGmv'?: AffiliateSeller202505GetMarketplaceCreatorPerformanceResponseDataCreatorLiveGmv;
    'liveGpm'?: AffiliateSeller202505GetMarketplaceCreatorPerformanceResponseDataCreatorLiveGpm;
    'liveGpmRange'?: AffiliateSeller202505GetMarketplaceCreatorPerformanceResponseDataCreatorLiveGpmRange;
    'nickname'?: string;
    'productOriginalPriceRange'?: AffiliateSeller202505GetMarketplaceCreatorPerformanceResponseDataCreatorProductOriginalPriceRange;
    'profileTtUri'?: string;
    'promotedProductNum'?: number;
    'selectionRegion'?: string;
    'topCollaboratedBrandIds'?: Array<string>;
    'unitsSold'?: number;
    'unitsSoldRange'?: AffiliateSeller202505GetMarketplaceCreatorPerformanceResponseDataCreatorUnitsSoldRange;
    'username'?: string;
    'videoGmv'?: AffiliateSeller202505GetMarketplaceCreatorPerformanceResponseDataCreatorVideoGmv;
    'videoGpm'?: AffiliateSeller202505GetMarketplaceCreatorPerformanceResponseDataCreatorVideoGpm;
    'videoGpmRange'?: AffiliateSeller202505GetMarketplaceCreatorPerformanceResponseDataCreatorVideoGpmRange;
    static discriminator: string | undefined;
    static attributeTypeMap: Array<{
        name: string;
        baseName: string;
        type: string;
    }>;
    static getAttributeTypeMap(): {
        name: string;
        baseName: string;
        type: string;
    }[];
}
//# sourceMappingURL=GetMarketplaceCreatorPerformanceResponseDataCreator.d.ts.map