/**
 * tiktok shop openapi
 * sdk for apis
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { RequestFile } from '../../models';
import { Product202309PartialEditProductRequestBodyReplicatedProductsSkusInventory } from './PartialEditProductRequestBodyReplicatedProductsSkusInventory';
import { Product202309PartialEditProductRequestBodyReplicatedProductsSkusPrice } from './PartialEditProductRequestBodyReplicatedProductsSkusPrice';

export class Product202309PartialEditProductRequestBodyReplicatedProductsSkus {
    /**
    * The SKU ID generated by TikTok Shop. Provide this for existing SKUs
    */
    'id'?: string;
    /**
    * SKU inventory information per warehouse.
    */
    'inventory'?: Array<Product202309PartialEditProductRequestBodyReplicatedProductsSkusInventory>;
    'price'?: Product202309PartialEditProductRequestBodyReplicatedProductsSkusPrice;
    /**
    * The seller_sku value of the source product above. - Valid length: 1-50 characters - Format: Text without spaces
    */
    'sellerSku'?: string;

    static discriminator: string | undefined = undefined;

    static attributeTypeMap: Array<{name: string, baseName: string, type: string}> = [
        {
            "name": "id",
            "baseName": "id",
            "type": "string"
        },
        {
            "name": "inventory",
            "baseName": "inventory",
            "type": "Array<Product202309PartialEditProductRequestBodyReplicatedProductsSkusInventory>"
        },
        {
            "name": "price",
            "baseName": "price",
            "type": "Product202309PartialEditProductRequestBodyReplicatedProductsSkusPrice"
        },
        {
            "name": "sellerSku",
            "baseName": "seller_sku",
            "type": "string"
        }    ];

    static getAttributeTypeMap() {
        return Product202309PartialEditProductRequestBodyReplicatedProductsSkus.attributeTypeMap;
    }
}

