/**
 * tiktok shop openapi
 * sdk for apis
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { RequestFile } from '../../models';
import { AffiliateCreator202504CreatorGeneratePublisherLinkRequestBodyMaterial } from './CreatorGeneratePublisherLinkRequestBodyMaterial';

export class AffiliateCreator202504CreatorGeneratePublisherLinkRequestBody {
    /**
    * Campaign ID. When `material.type==CAMPAIGN`, you must specify the ID of the campaign to which the materials belong.
    */
    'campaignId'?: string;
    'material'?: AffiliateCreator202504CreatorGeneratePublisherLinkRequestBodyMaterial;

    static discriminator: string | undefined = undefined;

    static attributeTypeMap: Array<{name: string, baseName: string, type: string}> = [
        {
            "name": "campaignId",
            "baseName": "campaign_id",
            "type": "string"
        },
        {
            "name": "material",
            "baseName": "material",
            "type": "AffiliateCreator202504CreatorGeneratePublisherLinkRequestBodyMaterial"
        }    ];

    static getAttributeTypeMap() {
        return AffiliateCreator202504CreatorGeneratePublisherLinkRequestBody.attributeTypeMap;
    }
}

