/**
 * tiktok shop openapi
 * sdk for apis
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { RequestFile } from '../../models';

export class AffiliateCreator202504CreatorGeneratePublisherLinkResponseDataSharingLinks {
    /**
    * Material ID.
    */
    'materialId'?: number;
    /**
    * This is the product promotion link that agencies can share with collaborated publishers. The publishers can post this link at their will.
    */
    'sharingLink'?: string;

    static discriminator: string | undefined = undefined;

    static attributeTypeMap: Array<{name: string, baseName: string, type: string}> = [
        {
            "name": "materialId",
            "baseName": "material_id",
            "type": "number"
        },
        {
            "name": "sharingLink",
            "baseName": "sharing_link",
            "type": "string"
        }    ];

    static getAttributeTypeMap() {
        return AffiliateCreator202504CreatorGeneratePublisherLinkResponseDataSharingLinks.attributeTypeMap;
    }
}

