/**
 * tiktok shop openapi
 * sdk for apis
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


import localVarRequest from 'request';
import http from 'http';

/* tslint:disable:no-unused-locals */
import { AffiliatePartner202505PartnerGenerateMultiAffiliateCampaignProductLinkRequestBody } from '../model/affiliatePartner/V202505/PartnerGenerateMultiAffiliateCampaignProductLinkRequestBody';
import { AffiliatePartner202505PartnerGenerateMultiAffiliateCampaignProductLinkResponse } from '../model/affiliatePartner/V202505/PartnerGenerateMultiAffiliateCampaignProductLinkResponse';

import { ObjectSerializer, Authentication, VoidAuth, Interceptor } from '../model/models';

import { HttpError, RequestFile } from './apis';

let defaultBasePath = 'https://open-api.tiktokglobalshop.com';

// ===============================================
// This file is autogenerated - Please do not edit
// ===============================================

export enum AffiliatePartnerV202505ApiApiKeys {
}

export class AffiliatePartnerV202505Api {
    protected _basePath = defaultBasePath;
    protected _defaultHeaders : any = {};
    protected _useQuerystring : boolean = false;

    static readonly apiName = 'AffiliatePartnerV202505Api' as const;

    protected authentications = {
        'default': <Authentication>new VoidAuth(),
    }

    protected interceptors: Interceptor[] = [];

    constructor(basePath?: string);
    constructor(basePathOrUsername: string, password?: string, basePath?: string) {
        if (password) {
            if (basePath) {
                this.basePath = basePath;
            }
        } else {
            if (basePathOrUsername) {
                this.basePath = basePathOrUsername
            }
        }
    }

    set useQuerystring(value: boolean) {
        this._useQuerystring = value;
    }

    set basePath(basePath: string) {
        this._basePath = basePath;
    }

    set defaultHeaders(defaultHeaders: any) {
        this._defaultHeaders = defaultHeaders;
    }

    get defaultHeaders() {
        return this._defaultHeaders;
    }

    get basePath() {
        return this._basePath;
    }

    public setDefaultAuthentication(auth: Authentication) {
        this.authentications.default = auth;
    }

    public setApiKey(key: AffiliatePartnerV202505ApiApiKeys, value: string) {
        (this.authentications as any)[AffiliatePartnerV202505ApiApiKeys[key]].apiKey = value;
    }

    public addInterceptor(interceptor: Interceptor) {
        this.interceptors.push(interceptor);
    }

    /**
     * This API offers the ability to generate promotion links for multiple products in a campaign.
     * @summary PartnerGenerateMultiAffiliateCampaignProductLink
     * @param campaignId The ID of the campaign
     * @param xTtsAccessToken 
     * @param contentType Allowed type: application/json
     * @param categoryAssetCipher The partner identifier used in API requests. Retrieve this value by using the [Get Authorized Category Assets API] (https://partner.tiktokshop.com/docv2/page/666012dd609d4402cc3be995).
     * @param PartnerGenerateMultiAffiliateCampaignProductLinkRequestBody 
     */
    public async CampaignsCampaignIdProductsPromotionLinksGenerateBatchPost (campaignId: string, xTtsAccessToken: string, contentType: string, categoryAssetCipher?: string, PartnerGenerateMultiAffiliateCampaignProductLinkRequestBody?: AffiliatePartner202505PartnerGenerateMultiAffiliateCampaignProductLinkRequestBody, options: {headers: {[name: string]: string}} = {headers: {}}) : Promise<{ response: http.IncomingMessage; body: AffiliatePartner202505PartnerGenerateMultiAffiliateCampaignProductLinkResponse;  }> {
        const localVarPath = this.basePath + '/affiliate_partner/202505/campaigns/{campaign_id}/products/promotion_links/generate_batch'
            .replace('{' + 'campaign_id' + '}', encodeURIComponent(String(campaignId)));
        let localVarQueryParameters: any = {};
        let localVarHeaderParams: any = (<any>Object).assign({}, this._defaultHeaders);
        const produces = ['application/json'];
        // give precedence to 'application/json'
        if (produces.indexOf('application/json') >= 0) {
            localVarHeaderParams.Accept = 'application/json';
        } else {
            localVarHeaderParams.Accept = produces.join(',');
        }
        let localVarFormParams: any = {};

        // verify required parameter 'campaignId' is not null or undefined
        if (campaignId === null || campaignId === undefined) {
            throw new Error('Required parameter campaignId was null or undefined when calling CampaignsCampaignIdProductsPromotionLinksGenerateBatchPost.');
        }

        // verify required parameter 'xTtsAccessToken' is not null or undefined
        if (xTtsAccessToken === null || xTtsAccessToken === undefined) {
            throw new Error('Required parameter xTtsAccessToken was null or undefined when calling CampaignsCampaignIdProductsPromotionLinksGenerateBatchPost.');
        }

        // verify required parameter 'contentType' is not null or undefined
        if (contentType === null || contentType === undefined) {
            throw new Error('Required parameter contentType was null or undefined when calling CampaignsCampaignIdProductsPromotionLinksGenerateBatchPost.');
        }

        if (categoryAssetCipher !== undefined) {
            localVarQueryParameters['category_asset_cipher'] = ObjectSerializer.serialize(categoryAssetCipher, "string");
        }

        localVarHeaderParams['x-tts-access-token'] = ObjectSerializer.serialize(xTtsAccessToken, "string");
        localVarHeaderParams['Content-Type'] = ObjectSerializer.serialize(contentType, "string");
        (<any>Object).assign(localVarHeaderParams, options.headers);

        let localVarUseFormData = false;

        let localVarRequestOptions: localVarRequest.Options = {
            method: 'POST',
            qs: localVarQueryParameters,
            headers: localVarHeaderParams,
            uri: localVarPath,
            useQuerystring: this._useQuerystring,
            json: true,
            body: ObjectSerializer.serialize(PartnerGenerateMultiAffiliateCampaignProductLinkRequestBody, "AffiliatePartner202505PartnerGenerateMultiAffiliateCampaignProductLinkRequestBody")
        };

        let authenticationPromise = Promise.resolve();
        authenticationPromise = authenticationPromise.then(() => this.authentications.default.applyToRequest(localVarRequestOptions));

        let interceptorPromise = authenticationPromise;
        for (const interceptor of this.interceptors) {
            interceptorPromise = interceptorPromise.then(() => interceptor(localVarRequestOptions));
        }

        return interceptorPromise.then(() => {
            if (Object.keys(localVarFormParams).length) {
                if (localVarUseFormData) {
                    (<any>localVarRequestOptions).formData = localVarFormParams;
                } else {
                    localVarRequestOptions.form = localVarFormParams;
                }
            }
            return new Promise<{ response: http.IncomingMessage; body: AffiliatePartner202505PartnerGenerateMultiAffiliateCampaignProductLinkResponse;  }>((resolve, reject) => {
                localVarRequest(localVarRequestOptions, (error, response, body) => {
                    if (error) {
                        reject(error);
                    } else {
                        if (response.statusCode && response.statusCode >= 200 && response.statusCode <= 299) {
                            body = ObjectSerializer.deserialize(body, "AffiliatePartner202505PartnerGenerateMultiAffiliateCampaignProductLinkResponse");
                            resolve({ response: response, body: body });
                        } else {
                            reject(new HttpError(response, body, response.statusCode));
                        }
                    }
                });
            });
        });
    }
}

export const AffiliatePartnerV202505ApiOperationNames = {
    CampaignsCampaignIdProductsPromotionLinksGenerateBatchPost: 'CampaignsCampaignIdProductsPromotionLinksGenerateBatchPost',
} as const


export type AffiliatePartnerV202505ApiOperationTypes = {
    CampaignsCampaignIdProductsPromotionLinksGenerateBatchPost: AffiliatePartnerV202505Api['CampaignsCampaignIdProductsPromotionLinksGenerateBatchPost'];
};

