/**
 * tiktok shop openapi
 * sdk for apis
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { RequestFile } from '../../models';

export class AffiliateCreator202505CreatorGenerateGeneralLinkResponseDataSharingLinks {
    /**
    * Material ID.
    */
    'materialId'?: string;
    /**
    * This is the product promotion link that agencies can share with collaborated creators. Creators can copy/paste this link into the web browser.  After you have the links, add the following request parameters and their corresponding values to the end of the link URL. When a user places an order using this link, the resulting e-commerce order will carry these parameters as part of its information: - event_id: Unique event id for each click - publisher_id: The unique publish_id assigned by CJ Nice to have - publisher_name: From CJ publisher profile. - device_type: 1-mobile, 2-desktop. - device_id: The clicks from the same device id can be aggregated as UV. - referrer_src: The URL of the webpage that a user came from before landing on the current share link.
    */
    'sharingLink'?: string;

    static discriminator: string | undefined = undefined;

    static attributeTypeMap: Array<{name: string, baseName: string, type: string}> = [
        {
            "name": "materialId",
            "baseName": "material_id",
            "type": "string"
        },
        {
            "name": "sharingLink",
            "baseName": "sharing_link",
            "type": "string"
        }    ];

    static getAttributeTypeMap() {
        return AffiliateCreator202505CreatorGenerateGeneralLinkResponseDataSharingLinks.attributeTypeMap;
    }
}

