/**
 * tiktok shop openapi
 * sdk for apis
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { RequestFile } from '../../models';

export class AffiliateSeller202412SendIMMessageRequestBody {
    /**
    * Message content, in JSON serialized string. Examples: - TEXT: {\"content\": \"simple text\"} - PRODUCT_CARD: {\"product_id\": \"12345\"} - TARGET_ COLLABORATION_CARD {\"target_collaboration_id\": \"1234\"} - FREE_SAMPLE_CARD {\"apply_id\": \"1234\"}  target_collaboration_id is Invitation group id.
    */
    'content'?: string;
    /**
    * Message type, with possible values: - TEXT - PRODUCT_CARD - TARGET_ COLLABORATION_CARD - FREE_SAMPLE_CARD Sending pictures is not currently supported.
    */
    'msgType'?: string;

    static discriminator: string | undefined = undefined;

    static attributeTypeMap: Array<{name: string, baseName: string, type: string}> = [
        {
            "name": "content",
            "baseName": "content",
            "type": "string"
        },
        {
            "name": "msgType",
            "baseName": "msg_type",
            "type": "string"
        }    ];

    static getAttributeTypeMap() {
        return AffiliateSeller202412SendIMMessageRequestBody.attributeTypeMap;
    }
}

