/**
 * tiktok shop openapi
 * sdk for apis
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { RequestFile } from '../../models';

export class AffiliateSeller202410SearchSellerAffiliateOrdersRequestBody {
    /**
    * Filter orders to show only those that are created on or after the specified date and time. Unix timestamp.  Note: `create_time_ge` and `create_time_lt` together constitute the creation time filter condition. - If `create_time_ge` is filled but `create_time_lt` is empty, `create_time_lt` will default to the current time. - If `create_time_lt` is filled but `create_time_ge` is empty, `create_time_ge` will default to the earliest shop time.
    */
    'createTimeGe'?: number;
    /**
    * Filter orders to show only those that are created before the specified date and time. Unix timestamp. Refer to notes in `create_time_ge` for more usage information.
    */
    'createTimeLt'?: number;
    /**
    * Filter orders by the associated affiliate program. This can be a campaign ID, target collaboration ID, or open collaboration ID.
    */
    'programId'?: string;

    static discriminator: string | undefined = undefined;

    static attributeTypeMap: Array<{name: string, baseName: string, type: string}> = [
        {
            "name": "createTimeGe",
            "baseName": "create_time_ge",
            "type": "number"
        },
        {
            "name": "createTimeLt",
            "baseName": "create_time_lt",
            "type": "number"
        },
        {
            "name": "programId",
            "baseName": "program_id",
            "type": "string"
        }    ];

    static getAttributeTypeMap() {
        return AffiliateSeller202410SearchSellerAffiliateOrdersRequestBody.attributeTypeMap;
    }
}

