export declare class Finance202309GetTransactionsbyOrderResponseDataStatementTransactionsSkuStatementTransactions {
    'actualReturnShippingFeeAmount'?: string;
    'actualShippingFeeAmount'?: string;
    'adjustmentAmount'?: string;
    'affiliateAdsCommissionAmount'?: string;
    'affiliateCommissionAmount'?: string;
    'affiliateCommissionBeforePit'?: string;
    'affiliatePartnerCommissionAmount'?: string;
    'afterSellerDiscountsSubtotalAmount'?: string;
    'currency'?: string;
    'customerOrderRefundAmount'?: string;
    'customerPaidShippingFeeAmount'?: string;
    'customerPaidShippingFeeRefundAmount'?: string;
    'customerPaymentAmount'?: string;
    'customerRefundAmount'?: string;
    'customerShippingFeeAmount'?: string;
    'customerShippingFeeOffsetAmount'?: string;
    'fbmShippingCostAmount'?: string;
    'fbtFulfillmentFeeAmount'?: string;
    'fbtShippingCostAmount'?: string;
    'feeAmount'?: string;
    'grossSalesAmount'?: string;
    'grossSalesRefundAmount'?: string;
    'isrIncomeTaxAmount'?: string;
    'ivaVatAmount'?: string;
    'netSalesAmount'?: string;
    'pitAmount'?: string;
    'platformCommissionAmount'?: string;
    'platformDiscountAmount'?: string;
    'platformDiscountRefundAmount'?: string;
    'platformRefundSubsidyAmount'?: string;
    'platformShippingFeeDiscountAmount'?: string;
    'productName'?: string;
    'promoShippingIncentiveAmount'?: string;
    'quantity'?: number;
    'referralFeeAmount'?: string;
    'refundAdministrationFeeAmount'?: string;
    'refundShippingCostDiscountAmount'?: string;
    'retailDeliveryFeeAmount'?: string;
    'retailDeliveryFeePaymentAmount'?: string;
    'retailDeliveryFeeRefundAmount'?: string;
    'returnShippingFeeAmount'?: string;
    'revenueAmount'?: string;
    'salesTaxAmount'?: string;
    'salesTaxPaymentAmount'?: string;
    'salesTaxRefundAmount'?: string;
    'sellerDiscountAmount'?: string;
    'sellerDiscountRefundAmount'?: string;
    'settlementAmount'?: string;
    'shippingCostAmount'?: string;
    'shippingCostDiscountAmount'?: string;
    'shippingFeeAmount'?: string;
    'shippingFeeSubsidyAmount'?: string;
    'shippingInsuranceFeeAmount'?: string;
    'signatureConfirmationFeeAmount'?: string;
    'skuId'?: string;
    'skuName'?: string;
    'transactionFeeAmount'?: string;
    static discriminator: string | undefined;
    static attributeTypeMap: Array<{
        name: string;
        baseName: string;
        type: string;
    }>;
    static getAttributeTypeMap(): {
        name: string;
        baseName: string;
        type: string;
    }[];
}
//# sourceMappingURL=GetTransactionsbyOrderResponseDataStatementTransactionsSkuStatementTransactions.d.ts.map